<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/es/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Gran Porte
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Conceptos de Batalla</h2><ul><li><a href='/es/Battles/GameBoard.aspx'>Tablero de Juego</a></li><li><a href='/es/Battles/Deploy.aspx'>Posicionar</a></li><li><a href='/es/Battles/Movement.aspx'>Movimiento</a></li><li><a href='/es/Battles/Rules.aspx'>Rules</a></li></ul><h2>Ataque</h2><ul><li><a href='/es/Battles/Range.aspx'>Alcance</a></li><li><a href='/es/Battles/Catapult.aspx'>Catapulta</a></li><li><a href='/es/Battles/ParalyseAttack.aspx'>Ataque Paralizador</a></li><li><a href='/es/Battles/Replicator.aspx'>Replicador</a></li><li><a href='/es/Battles/StrikeBack.aspx'>Contraataque</a></li><li><a href='/es/Battles/InfestationAttack.aspx'>Ataque Venenoso</a></li><li><a href='/es/Battles/RemoveAbilityAttack.aspx'>Remover Habilidad</a></li><li><a href='/es/Battles/TripleAttack.aspx'>Ataque Triple</a></li><li><a href='/es/Battles/BombAttack.aspx'>Ataque Bomba</a></li><li><a href='/es/Battles/Rebound.aspx'>Rebote</a></li></ul><h2>Categoría</h2><ul><li><a href='/es/Battles/Light.aspx'>Pequeño Porte</a></li><li><a href='/es/Battles/Medium.aspx'>Médio Porte</a></li><li><a href='/es/Battles/Heavy.aspx'>Gran Porte</a></li><li><a href='/es/Battles/Ultimate.aspx'>Suprema</a></li><li><a href='/es/Battles/Special.aspx'>Especial</a></li></ul><h2>Tipo de Batalla</h2><ul><li><a href='/es/Battles/TotalAnnihilation.aspx'>Destrucción Total</a></li><li><a href='/es/Battles/Regicide.aspx'>Regicidio</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Unidades de Gran Porte</h1>
<div class="content">
    Las unidades <a href='/es/Battles/Heavy.aspx'>Gran Porte</a> simbolizan poder de ataque. Son las <a href='/es/UnitIndex.aspx'>Unidades de Combate</a> mas poderosas, ya sea en ataque, o
    en defensa, siendo solamente limitadas por el tipo de <a href='/es/Battles/Movement.aspx'>Movimiento</a> y <a href='/es/Battles/Movement.aspx#MovCost'>Costo de Movimiento</a>. Las unidades  <a href='/es/Battles/Heavy.aspx'>Gran Porte</a> también
    son conocidas por su largo <a href='/es/Battles/Range.aspx'>Alcance</a>.
    <p />
    Naturalmente tenemos <a href='/es/UnitIndex.aspx'>Unidades de Combate</a> de <a href='/es/Battles/Heavy.aspx'>Gran Porte</a> que no siguén exactamente este padrón. Por ejemplo la <a class='doomer' href='/es/Unit/Doomer.aspx'>Aniquiladora</a>,
    la <a class='blackwidow' href='/es/Unit/BlackWidow.aspx'>Viuda Negra</a> y el <a class='taurus' href='/es/Unit/Taurus.aspx'>Toro</a> sólo tienen 3 de <a href='/es/Battles/Range.aspx'>Alcance</a>, pero son compensados por mas libertad de <a href='/es/Battles/Movement.aspx'>Movimiento</a>,
    o poder extra.
    <p />
    Las unidades <a href='/es/Battles/Heavy.aspx'>Gran Porte</a> tienen que tener especial atención a la <a class='rain' href='/es/Unit/Rain.aspx'>Lluvia</a> y a la <a class='darkrain' href='/es/Unit/DarkRain.aspx'>Lluvia Sombría</a>, que tienen  bonos especiales de ataque.
    <p />
    Lista de unidades de <a href='/es/Battles/Heavy.aspx'>Gran Porte</a>:
  </div>
	<ul class='imageList'><li><a href='/es/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Fist' /></a></li><li><a href='/es/Unit/Nova.aspx'><img class='nova' src='http://resources.orionsbelt.eu/Images/Common/Units/nova.png' alt='Nova' /></a></li><li><a href='/es/Unit/HiveKing.aspx'><img class='hiveking' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveking.png' alt='Rey de la Colmena' /></a></li><li><a href='/es/Unit/Bozer.aspx'><img class='bozer' src='http://resources.orionsbelt.eu/Images/Common/Units/bozer.png' alt='Bozer' /></a></li><li><a href='/es/Unit/Doomer.aspx'><img class='doomer' src='http://resources.orionsbelt.eu/Images/Common/Units/doomer.png' alt='Aniquiladora' /></a></li><li><a href='/es/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titan' /></a></li><li><a href='/es/Unit/BlackWidow.aspx'><img class='blackwidow' src='http://resources.orionsbelt.eu/Images/Common/Units/blackwidow.png' alt='Viuda Negra' /></a></li><li><a href='/es/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='CaptainWolf' /></a></li><li><a href='/es/Unit/Fenix.aspx'><img class='fenix' src='http://resources.orionsbelt.eu/Images/Common/Units/fenix.png' alt='Fénix' /></a></li><li><a href='/es/Unit/Taurus.aspx'><img class='taurus' src='http://resources.orionsbelt.eu/Images/Common/Units/taurus.png' alt='Toro' /></a></li><li><a href='/es/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Commander Fox' /></a></li><li><a href='/es/Unit/HeavySeeker.aspx'><img class='heavyseeker' src='http://resources.orionsbelt.eu/Images/Common/Units/heavyseeker.png' alt='Mega Buscador' /></a></li><li><a href='/es/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Silver Beard' /></a></li><li><a href='/es/Unit/DarkTaurus.aspx'><img class='darktaurus' src='http://resources.orionsbelt.eu/Images/Common/Units/darktaurus.png' alt='Toro Oscuro' /></a></li><li><a href='/es/Unit/DarkCrusader.aspx'><img class='darkcrusader' src='http://resources.orionsbelt.eu/Images/Common/Units/darkcrusader.png' alt='Cruzador Sombrio' /></a></li><li><a href='/es/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Barba de Metal' /></a></li><li><a href='/es/Unit/Crusader.aspx'><img class='crusader' src='http://resources.orionsbelt.eu/Images/Common/Units/crusader.png' alt='Cruzador' /></a></li></ul>
	
</asp:Content>