<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/es/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Médio Porte
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Conceptos de Batalla</h2><ul><li><a href='/es/Battles/GameBoard.aspx'>Tablero de Juego</a></li><li><a href='/es/Battles/Deploy.aspx'>Posicionar</a></li><li><a href='/es/Battles/Movement.aspx'>Movimiento</a></li><li><a href='/es/Battles/Rules.aspx'>Rules</a></li></ul><h2>Ataque</h2><ul><li><a href='/es/Battles/Range.aspx'>Alcance</a></li><li><a href='/es/Battles/Catapult.aspx'>Catapulta</a></li><li><a href='/es/Battles/ParalyseAttack.aspx'>Ataque Paralizador</a></li><li><a href='/es/Battles/Replicator.aspx'>Replicador</a></li><li><a href='/es/Battles/StrikeBack.aspx'>Contraataque</a></li><li><a href='/es/Battles/InfestationAttack.aspx'>Ataque Venenoso</a></li><li><a href='/es/Battles/RemoveAbilityAttack.aspx'>Remover Habilidad</a></li><li><a href='/es/Battles/TripleAttack.aspx'>Ataque Triple</a></li><li><a href='/es/Battles/BombAttack.aspx'>Ataque Bomba</a></li><li><a href='/es/Battles/Rebound.aspx'>Rebote</a></li></ul><h2>Categoría</h2><ul><li><a href='/es/Battles/Light.aspx'>Pequeño Porte</a></li><li><a href='/es/Battles/Medium.aspx'>Médio Porte</a></li><li><a href='/es/Battles/Heavy.aspx'>Gran Porte</a></li><li><a href='/es/Battles/Ultimate.aspx'>Suprema</a></li><li><a href='/es/Battles/Special.aspx'>Especial</a></li></ul><h2>Tipo de Batalla</h2><ul><li><a href='/es/Battles/TotalAnnihilation.aspx'>Destrucción Total</a></li><li><a href='/es/Battles/Regicide.aspx'>Regicidio</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Unidades de Porte Médio </h1>
<div class="content">
    Las unidades de <a href='/es/Battles/Medium.aspx'>Médio Porte</a> son categorizadas como las mas equilibradas del juego. No son las mas rápidas,
    ni las mas lentas, no son las mas fortes ni las mas debiles. Este equilíbrio de fuerza y libertad de 
    <a href='/es/Battles/Movement.aspx'>Movimiento</a> hacen  que con las unidades  <a href='/es/Battles/Medium.aspx'>Médio Porte</a> seán el corazón de cualquier <a href='/es/Universe/Fleet.aspx'>Flota</a>.
    <p />
    A pesar de ser mas debiles que las unidades <a href='/es/Battles/Heavy.aspx'>Gran Porte</a>, muchas veces su mobilidad extra, aliada a alguna
    <a href='/es/Battles/DispensableUnits.aspx'>Carne de Cañon</a> hacen que sean mejor llevadas. Como enemigas naturales, las unidades <a href='/es/Battles/Medium.aspx'>Médio Porte</a> deven tener 
    especial atención a las <a class='kamikaze' href='/es/Unit/Kamikaze.aspx'>Suicida</a> y a los <a class='seeker' href='/es/Unit/Seeker.aspx'>Buscador</a>.
    <p />
    Lista de unidades  <a href='/es/Battles/Medium.aspx'>Médio Porte</a>:
  </div>
	<ul class='imageList'><li><a href='/es/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Suicida' /></a></li><li><a href='/es/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Araña' /></a></li><li><a href='/es/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='Protector de la Colmena' /></a></li><li><a href='/es/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Perforador' /></a></li><li><a href='/es/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vector' /></a></li><li><a href='/es/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Gusano' /></a></li><li><a href='/es/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Flagelo' /></a></li><li><a href='/es/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/es/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Escarabajo' /></a></li><li><a href='/es/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Aguila' /></a></li><li><a href='/es/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Pretoriana' /></a></li><li><a href='/es/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Aguijón' /></a></li><li><a href='/es/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/es/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Destructor' /></a></li><li><a href='/es/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/es/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/es/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Ataque',Defense:'Defensa',MovementCost:'Costo de Movimiento',Range:'Alcance',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Commander Fox'},HiveProtector:{Name:'Protector de la Colmena'},Doomer:{Name:'Aniquiladora'},Cypher:{Name:'Cypher'},Stinger:{Name:'Aguijón'},CaptainWolf:{Name:'CaptainWolf'},Destroyer:{Name:'Destructor'},Myst:{Name:'Myst'},Scarab:{Name:'Escarabajo'},Toxic:{Name:'Toxico'},Fist:{Name:'Fist'},Flag:{Name:'Bandera'},DarkTaurus:{Name:'Toro Oscuro'},Egg:{Name:'Huevo'},Jumper:{Name:'Jumper'},BattleMoon:{Name:'Luna de Batalla'},MetallicBeard:{Name:'Barba de Metal'},DarkCrusader:{Name:'Cruzador Sombrio'},Scourge:{Name:'Flagelo'},Crawler:{Name:'Crawler'},Rain:{Name:'Lluvia'},Samurai:{Name:'Samurai'},Panther:{Name:'Pantera'},Queen:{Name:'Reina'},DarkRain:{Name:'Lluvia Sombría'},Worm:{Name:'Gusano'},Taurus:{Name:'Toro'},Kamikaze:{Name:'Suicida'},Pretorian:{Name:'Pretoriana'},Seeker:{Name:'Buscador'},Nova:{Name:'Nova'},Maggot:{Name:'Larva'},BlackWidow:{Name:'Viuda Negra'},Crusader:{Name:'Cruzador'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Rey de la Colmena'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Perforador'},Eagle:{Name:'Aguila'},Blinker:{Name:'Parpadeante'},Sentry:{Name:'Sentry'},Vector:{Name:'Vector'},Walker:{Name:'Walker'},Titan:{Name:'Titan'},SilverBeard:{Name:'Silver Beard'},Fenix:{Name:'Fénix'},Interceptor:{Name:'Interceptador'},Reaper:{Name:'Reaper'},Raptor:{Name:'Raptor'},Spider:{Name:'Araña'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Mega Buscador'}};</script>
	
</asp:Content>