<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/fr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Médium
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Concepts de Bataille</h2><ul><li><a href='/fr/Battles/GameBoard.aspx'>Plateau de jeu</a></li><li><a href='/fr/Battles/Deploy.aspx'>Déploiement</a></li><li><a href='/fr/Battles/Movement.aspx'>Mouvement</a></li><li><a href='/fr/Battles/Rules.aspx'>Rules</a></li></ul><h2>Attaque</h2><ul><li><a href='/fr/Battles/Range.aspx'>Portée</a></li><li><a href='/fr/Battles/Catapult.aspx'>Catapulte</a></li><li><a href='/fr/Battles/ParalyseAttack.aspx'>Attaque paralysante</a></li><li><a href='/fr/Battles/Replicator.aspx'>Réplicateur</a></li><li><a href='/fr/Battles/StrikeBack.aspx'>Contre-attaque</a></li><li><a href='/fr/Battles/InfestationAttack.aspx'>Attaque Vénéneuse</a></li><li><a href='/fr/Battles/RemoveAbilityAttack.aspx'>Attaque annulant les habiletés</a></li><li><a href='/fr/Battles/TripleAttack.aspx'>Attaque triple</a></li><li><a href='/fr/Battles/BombAttack.aspx'>Attaque explosive</a></li><li><a href='/fr/Battles/Rebound.aspx'>Rebond</a></li></ul><h2>Catégorie</h2><ul><li><a href='/fr/Battles/Light.aspx'>Légère</a></li><li><a href='/fr/Battles/Medium.aspx'>Médium</a></li><li><a href='/fr/Battles/Heavy.aspx'>Lourde</a></li><li><a href='/fr/Battles/Ultimate.aspx'>Ultime</a></li><li><a href='/fr/Battles/Special.aspx'>Spécial</a></li></ul><h2>Type de Combat</h2><ul><li><a href='/fr/Battles/TotalAnnihilation.aspx'>Anihilation totale</a></li><li><a href='/fr/Battles/Regicide.aspx'>Régicide</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Medium Units</h1>
<div class="content">
    <a href='/fr/Battles/Medium.aspx'>Médium</a> units are known for being the most balanced ones on the game. They aren't the fastest, nor are
    they the slowest. They aren't the strongest, but they aren't the weakest. This balance of force and liberty
    of <a href='/fr/Battles/Movement.aspx'>Mouvement</a> makes <a href='/fr/Battles/Medium.aspx'>Médium</a> units the heart of any <a href='/fr/Universe/Fleet.aspx'>Escadrile</a>.
    <p />
    <a href='/fr/Battles/Medium.aspx'>Médium</a> units may be weaker thatn <a href='/fr/Battles/Heavy.aspx'>Lourde</a> units, but may times the extra mobility with some help from
    <a href='/fr/Battles/DispensableUnits.aspx'>Chair à canon</a> turns them into winners. As natural enemies, <a href='/fr/Battles/Medium.aspx'>Médium</a> units should avoid the
    <a class='kamikaze' href='/fr/Unit/Kamikaze.aspx'>Kamikaze</a> and the <a class='seeker' href='/fr/Unit/Seeker.aspx'>Ouvrier</a>.
    <p />
    <a href='/fr/Battles/Medium.aspx'>Médium</a> units:
  </div>
	<ul class='imageList'><li><a href='/fr/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Kamikaze' /></a></li><li><a href='/fr/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Araignée' /></a></li><li><a href='/fr/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='protecteur coloniale' /></a></li><li><a href='/fr/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Perçeur' /></a></li><li><a href='/fr/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vecteur' /></a></li><li><a href='/fr/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Vers' /></a></li><li><a href='/fr/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Scourge' /></a></li><li><a href='/fr/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/fr/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Scarabé' /></a></li><li><a href='/fr/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Aigle' /></a></li><li><a href='/fr/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Prédateur' /></a></li><li><a href='/fr/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Piqueur' /></a></li><li><a href='/fr/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/fr/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Destructeur' /></a></li><li><a href='/fr/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/fr/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/fr/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Attaque',Defense:'Défense',MovementCost:'Coût de mouvement',Range:'Portée',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Commander Fox'},HiveProtector:{Name:'protecteur coloniale'},Doomer:{Name:'Anihilateur'},Cypher:{Name:'Cypher'},Stinger:{Name:'Piqueur'},CaptainWolf:{Name:'CaptainWolf'},Destroyer:{Name:'Destructeur'},Myst:{Name:'Myst'},Scarab:{Name:'Scarabé'},Toxic:{Name:'Toxique'},Fist:{Name:'Fist'},Flag:{Name:'Drapeau'},DarkTaurus:{Name:'Taureau Noir'},Egg:{Name:'Oeuf'},Jumper:{Name:'Jumper'},BattleMoon:{Name:'Lune de Combat'},MetallicBeard:{Name:'Metallic Beard'},DarkCrusader:{Name:'Croiseur Noir'},Scourge:{Name:'Scourge'},Crawler:{Name:'Crawler'},Rain:{Name:'Bruine'},Samurai:{Name:'Samurai'},Panther:{Name:'Panthère'},Queen:{Name:'Reine'},DarkRain:{Name:'Bruine Noire'},Worm:{Name:'Vers'},Taurus:{Name:'Taureau'},Kamikaze:{Name:'Kamikaze'},Pretorian:{Name:'Prédateur'},Seeker:{Name:'Ouvrier'},Nova:{Name:'Nova'},Maggot:{Name:'Asticot'},BlackWidow:{Name:'Veuve Noire'},Crusader:{Name:'Croiseur'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Roi coloniale'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Perçeur'},Eagle:{Name:'Aigle'},Blinker:{Name:'Téléporteur'},Sentry:{Name:'Sentry'},Vector:{Name:'Vecteur'},Walker:{Name:'Walker'},Titan:{Name:'Titan'},SilverBeard:{Name:'Silver Beard'},Fenix:{Name:'Fénix'},Interceptor:{Name:'Intercepteur'},Reaper:{Name:'Reaper'},Raptor:{Name:'Raptor'},Spider:{Name:'Araignée'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Ouvrier lourd'}};</script>
	
</asp:Content>