<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/es/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Comerciante
</asp:Content>

<asp:Content ContentPlaceHolderID="menu" runat="server">
	<h2>Misiones</h2><ul><li><a href='/es/PirateQuests.aspx'>Pirata</a></li><li><a href='/es/RaceQuests.aspx'>Raza</a></li><li><a href='/es/ColonizerQuests.aspx'>Colonizador</a></li><li><a href='/es/GladiatorQuests.aspx'>Gladiador</a></li><li><a href='/es/BattleQuests.aspx'>Batalla</a></li><li><a href='/es/PMQuestQuests.aspx'>Gestión de Planetas</a></li><li><a href='/es/MerchantQuests.aspx'>Comerciante</a></li><li><a href='/es/BountyHunterQuests.aspx'>Cazador de Premios</a></li><li><a href='/es/MercsQuests.aspx'>Mercs</a></li><li><a href='/es/SpaceForceQuests.aspx'>Space Force</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Comerciante</h1><div class='description'><a href='/es/Quests.aspx'>Misiones</a> que se enfocan en <a href='/es/Commerce/TradeRoutes.aspx'>Rutas Comerciales</a>.</div><h2>Misiones de Comerciante</h2><table class='table' id='quests'><tr><th colspan='2'>Utopianos</th><th colspan='2'>Renegados</th><th colspan='2'>Levyr</th></tr><tr><td colspan='6'><a href='Quest/GetAllPrivateZoneResources.aspx'>Tomar todos los recursos que tienes en la zona privada</a></td></tr><tr><td colspan='6'><a href='Quest/FindOneMarketQuest.aspx'>Encontrar un mercado en la zona pública</a></td></tr><tr><td colspan='6'><a href='Quest/FirstTradeRouteQuest.aspx'>Completar una ruta comercial</a></td></tr><tr><td colspan='6'><a href='Quest/CompleteForLevel1TradeRoutes.aspx'>Completar cuatro rutas comerciales de Herramientas o Mantenimiento</a></td></tr><tr><td colspan='6'><a href='Quest/Complete10Level1TradeRoutes.aspx'>Completar diez rutas comerciales de Herramientas o Mantenimiento en 24 horas</a></td></tr><tr><td colspan='6'><a href='Quest/BringToolsAndSuppliesToMarketLevel3.aspx'>Transportar Herramientas y Mantenimientos para un Mercado de nivel 3 ou nivel 5</a></td></tr><tr><td colspan='6'><a href='Quest/Complete8Level3TradeRoutes.aspx'>Complete 8 trade routes using Alcohol or Medicine</a></td></tr><tr><td colspan='6'><a href='Quest/Complete12Level3TradeRoutes.aspx'>Complete 12 trade routes using Alcohol or Medicine in 24 hours</a></td></tr><tr><td colspan='6'><a href='Quest/BringMedicineAndAlcoholToMarketLevel7.aspx'>Bring Medicine and Alcohol to a Market level 7</a></td></tr><tr><td colspan='6'><a href='Quest/Complete12Level7TradeRoutes.aspx'>Complete 12 trade routes using Mercury or Diamonds</a></td></tr><tr><td colspan='6'><a href='Quest/Complete16Level7TradeRoutes.aspx'>Complete 16 trade routes using Mercury or Diamonds in 24 hours</a></td></tr><tr><td colspan='6'><a href='Quest/BringMercuryAndDiamondsToMarketLevel10.aspx'>Bring Mercury and Diamonds to a level 10 Market</a></td></tr><tr><td colspan='6'><a href='Quest/Complete16Level10TradeRoutes.aspx'>Complete 16 trade routes using Animals or Cosmic Dust</a></td></tr><tr><td colspan='6'><a href='Quest/Complete20Level10TradeRoutes.aspx'>Complete 20 trade routes using Animals or Cosmic Dust in 24 hours</a></td></tr></table>
	
</asp:Content>