<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/de/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Medium
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Kampf-Konzepte</h2><ul><li><a href='/de/Battles/GameBoard.aspx'>Spielbrett</a></li><li><a href='/de/Battles/Deploy.aspx'>Positionieren</a></li><li><a href='/de/Battles/Movement.aspx'>Beweglichkeit</a></li><li><a href='/de/Battles/Rules.aspx'>Regeln</a></li></ul><h2>Angriff</h2><ul><li><a href='/de/Battles/Range.aspx'>Reichweite</a></li><li><a href='/de/Battles/Catapult.aspx'>Katapult</a></li><li><a href='/de/Battles/ParalyseAttack.aspx'>Paralisier-Attacke</a></li><li><a href='/de/Battles/Replicator.aspx'>Replikator</a></li><li><a href='/de/Battles/StrikeBack.aspx'>Gegenangriff</a></li><li><a href='/de/Battles/InfestationAttack.aspx'>Gift-Attacke</a></li><li><a href='/de/Battles/RemoveAbilityAttack.aspx'>Fähigkeiten entfernen</a></li><li><a href='/de/Battles/TripleAttack.aspx'>Dreifach-Attacke</a></li><li><a href='/de/Battles/BombAttack.aspx'>Bombenattacke</a></li><li><a href='/de/Battles/Rebound.aspx'>Rückprall</a></li></ul><h2>Kategorie</h2><ul><li><a href='/de/Battles/Light.aspx'>Licht</a></li><li><a href='/de/Battles/Medium.aspx'>Medium</a></li><li><a href='/de/Battles/Heavy.aspx'>Schwer</a></li><li><a href='/de/Battles/Ultimate.aspx'>Höchste</a></li><li><a href='/de/Battles/Special.aspx'>Spezial</a></li></ul><h2>Schlacht-Typ</h2><ul><li><a href='/de/Battles/TotalAnnihilation.aspx'>Totale Zerstörung</a></li><li><a href='/de/Battles/Regicide.aspx'>Königsmord</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Medium Einheiten</h1>
<div class="content">
    <a href='/de/Battles/Medium.aspx'>Medium</a> Einheiten sind dafür bekannt dass sie die ausgewogensten im Spiel sind. Sie sind nicht die 
    schnellsten, aber auch nicht die langsamsten. Sie sind nicht die stärksten, aber auch nicht die 
    schwächsten. Diese Ausgeglichenheit von Freiheit an [Bewegungen] macht <a href='/de/Battles/Medium.aspx'>Medium</a> Einheiten zum Herz 
    jeder [Flotte].
    <p>
    <a href='/de/Battles/Medium.aspx'>Medium</a> Einheiten mögen zwar schwächer sein als<a href='/de/Battles/Heavy.aspx'>Schwer</a> Einheiten, aber die extra Mobilität 
    und Hilfe von <a href='/de/Battles/DispensableUnits.aspx'>Kanonenfutter</a> macht sie zu Gewinnern. Als natürlich Feinde, sollten <a href='/de/Battles/Medium.aspx'>Medium</a> 
    Einheiten die <a class='kamikaze' href='/de/Unit/Kamikaze.aspx'>Kamikaze</a> und die <a class='seeker' href='/de/Unit/Seeker.aspx'>Sucher</a> vermeiden.
    </p><p>
    <a href='/de/Battles/Medium.aspx'>Medium</a> Einheiten:
  </p></div>
	<ul class='imageList'><li><a href='/de/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Kamikaze' /></a></li><li><a href='/de/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Spinne' /></a></li><li><a href='/de/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='Bienenstock Beschützer' /></a></li><li><a href='/de/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Bohrer' /></a></li><li><a href='/de/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vektor' /></a></li><li><a href='/de/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Wurm' /></a></li><li><a href='/de/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Scourge' /></a></li><li><a href='/de/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/de/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Skarabäus' /></a></li><li><a href='/de/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Adler' /></a></li><li><a href='/de/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Praetorian' /></a></li><li><a href='/de/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Stachel' /></a></li><li><a href='/de/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/de/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Zerstörer' /></a></li><li><a href='/de/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/de/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Kriecher' /></a></li><li><a href='/de/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Angriff',Defense:'Verteidigung',MovementCost:'Bewegungskosten',Range:'Reichweite',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Kommander Fox'},HiveProtector:{Name:'Bienenstock Beschützer'},Doomer:{Name:'Doomer'},Cypher:{Name:'Cypher'},Stinger:{Name:'Stachel'},CaptainWolf:{Name:'Kapitän Wolf'},Destroyer:{Name:'Zerstörer'},Myst:{Name:'Myst'},Scarab:{Name:'Skarabäus'},Toxic:{Name:'Toxisch'},Fist:{Name:'Faust'},Flag:{Name:'Flagge'},DarkTaurus:{Name:'Dunkler Taurus'},Egg:{Name:'Ei'},Jumper:{Name:'Springer'},BattleMoon:{Name:'Mond-Schlacht'},MetallicBeard:{Name:'Metallischer Bart'},DarkCrusader:{Name:'Dunkler Kreuzfahrer'},Scourge:{Name:'Scourge'},Crawler:{Name:'Kriecher'},Rain:{Name:'Regen'},Samurai:{Name:'Samurai'},Panther:{Name:'Panther'},Queen:{Name:'Königin'},DarkRain:{Name:'Dunkler Regen'},Worm:{Name:'Wurm'},Taurus:{Name:'Taurus'},Kamikaze:{Name:'Kamikaze'},Pretorian:{Name:'Praetorian'},Seeker:{Name:'Sucher'},Nova:{Name:'Nova'},Maggot:{Name:'Made'},BlackWidow:{Name:'Schwarze Witwe'},Crusader:{Name:'Kreuzfahrer'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Bienenstock König'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Bohrer'},Eagle:{Name:'Adler'},Blinker:{Name:'Blinker'},Sentry:{Name:'Sentry'},Vector:{Name:'Vektor'},Walker:{Name:'Walker'},Titan:{Name:'Titan'},SilverBeard:{Name:'Silberbart'},Fenix:{Name:'Fenix'},Interceptor:{Name:'Abfangjäger'},Reaper:{Name:'Reaper'},Raptor:{Name:'Raptor'},Spider:{Name:'Spinne'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Mega Sucher'}};</script>
	
</asp:Content>