<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/fr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Marchand
</asp:Content>

<asp:Content ContentPlaceHolderID="menu" runat="server">
	<h2>Quêtes</h2><ul><li><a href='/fr/PirateQuests.aspx'>Pirate</a></li><li><a href='/fr/RaceQuests.aspx'>Race</a></li><li><a href='/fr/ColonizerQuests.aspx'>Coloniseur</a></li><li><a href='/fr/GladiatorQuests.aspx'>Gladiateur</a></li><li><a href='/fr/BattleQuests.aspx'>Bataille</a></li><li><a href='/fr/PMQuestQuests.aspx'>Gérer les planètes</a></li><li><a href='/fr/MerchantQuests.aspx'>Marchand</a></li><li><a href='/fr/BountyHunterQuests.aspx'>Chasseur de prime</a></li><li><a href='/fr/MercsQuests.aspx'>Mercs</a></li><li><a href='/fr/SpaceForceQuests.aspx'>Space Force</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Marchand</h1><div class='description'><a href='/fr/Quests.aspx'>Quêtes</a> that focus on <a href='/fr/Commerce/TradeRoutes.aspx'>Routes commerciales</a>.</div><h2>Marchand Quêtes</h2><table class='table' id='quests'><tr><th colspan='2'>Utopians</th><th colspan='2'>Renegades</th><th colspan='2'>Levyr</th></tr><tr><td colspan='6'><a href='Quest/GetAllPrivateZoneResources.aspx'>Attraper toutes les ressources sur votre zone privée</a></td></tr><tr><td colspan='6'><a href='Quest/FindOneMarketQuest.aspx'>Trouvez un macrhé sur la zone publique</a></td></tr><tr><td colspan='6'><a href='Quest/FirstTradeRouteQuest.aspx'>Compléter une route commerciale</a></td></tr><tr><td colspan='6'><a href='Quest/CompleteForLevel1TradeRoutes.aspx'>Terminer 4 routes commerciales en utilisant outils ou provisions.</a></td></tr><tr><td colspan='6'><a href='Quest/Complete10Level1TradeRoutes.aspx'>Complétez 10 routes commerciales en utilisant les outils ou approvisionnements en 24 heures</a></td></tr><tr><td colspan='6'><a href='Quest/BringToolsAndSuppliesToMarketLevel3.aspx'>Apportez une esadrille avec des outils et approvisionnements à un marché de niveau 3 ou 5</a></td></tr><tr><td colspan='6'><a href='Quest/Complete8Level3TradeRoutes.aspx'>Complétez 10 routes commerciales en utilisant l'alcool ou des médicaments.</a></td></tr><tr><td colspan='6'><a href='Quest/Complete12Level3TradeRoutes.aspx'>Terminer 12 routes commerciales en utilisant de l'alcool et de la médecine en 24 heures.</a></td></tr><tr><td colspan='6'><a href='Quest/BringMedicineAndAlcoholToMarketLevel7.aspx'>Apporter une escadrille ayant alcool et médicament à un marché niveau 7</a></td></tr><tr><td colspan='6'><a href='Quest/Complete12Level7TradeRoutes.aspx'>Terminer 12 routes commerciales en utilisant du mercure ou des diamants</a></td></tr><tr><td colspan='6'><a href='Quest/Complete16Level7TradeRoutes.aspx'>Terminer 16 routes commerciales en utilisant des diamants ou du mercure en 24 heures.</a></td></tr><tr><td colspan='6'><a href='Quest/BringMercuryAndDiamondsToMarketLevel10.aspx'>Apporter une escadrille ayant du mercure et des diamants à un marché niveau 10</a></td></tr><tr><td colspan='6'><a href='Quest/Complete16Level10TradeRoutes.aspx'>Complétez 16 routes commerciales avec les animaux ou la poudre cosmique</a></td></tr><tr><td colspan='6'><a href='Quest/Complete20Level10TradeRoutes.aspx'>Terminer 20 routes commerciales en utilisant des animaux ou de la poudre cosmique en 24 heures.</a></td></tr></table>
	
</asp:Content>