<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/fr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Mobs
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Mobs</h1><p><div class="content">
    Un <u>A.I.</u> est un enemmie controlé par le jeu( intelligence artificiel). Il est possible de rencontrer des A.I. durant vos <a href='/fr/Universe/Travel.aspx'>Voyage</a> à travers l'<a href='/fr/Universe/Default.aspx'>Univers</a>. Vous pouvez aussi faire des <a href='/fr/Quests.aspx'>Quêtes</a> où il vous faudra éliminer certains A.I.. Les <a href='/fr/UnitIndex.aspx'>Unités de Combat</a> des A.I. et vous pouvez en avoir vous-même en fesant des <a href='/fr/Quests.aspx'>Quêtes</a> où en magasinant à la <a href='/fr/Commerce/AuctionHouse.aspx'>Maison des enchères</a>.
  </div></p><table class='table'><tr><th>Race</td><th>Unités de Combat</td></tr><tr><td><a href='/fr/Race/Mercs.aspx'>Mercs</a></td><td><ul class='unitIndexList'><li><a href='/fr/Unit/Sentry.aspx'><img class='sentry' src='http://resources.orionsbelt.eu/Images/Common/Units/sentry.png' alt='Sentry' /></a></li><li><a href='/fr/Unit/Reaper.aspx'><img class='reaper' src='http://resources.orionsbelt.eu/Images/Common/Units/reaper.png' alt='Reaper' /></a></li><li><a href='/fr/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Scourge' /></a></li><li><a href='/fr/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li><li><a href='/fr/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titan' /></a></li><li><a href='/fr/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Silver Beard' /></a></li><li><a href='/fr/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Metallic Beard' /></a></li></ul></td></tr><tr><td>[SpaceForce]</td><td><ul class='unitIndexList'><li><a href='/fr/Unit/Jumper.aspx'><img class='jumper' src='http://resources.orionsbelt.eu/Images/Common/Units/jumper.png' alt='Jumper' /></a></li><li><a href='/fr/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/fr/Unit/Cypher.aspx'><img class='cypher' src='http://resources.orionsbelt.eu/Images/Common/Units/cypher.png' alt='Cypher' /></a></li><li><a href='/fr/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/fr/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Fist' /></a></li><li><a href='/fr/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Commander Fox' /></a></li><li><a href='/fr/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='CaptainWolf' /></a></li></ul></td></tr></table>
	
</asp:Content>