<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/es/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Ataque Devastación
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Universo</h2><ul><li><a href='/es/Universe/PrivateZone.aspx'>Zona Privada</a></li><li><a href='/es/Universe/HotZone.aspx'>Zona Pública</a></li><li><a href='/es/Universe/Coordinates.aspx'>Coordenadas</a></li></ul><h2>Accione en el Universo</h2><ul><li><a href='/es/Universe/Travel.aspx'>Viajar</a></li><li><a href='/es/Universe/LineOfSight.aspx'>Área de Visión</a></li><li><a href='/es/Universe/Colonize.aspx'>Colonizar</a></li><li><a href='/es/Universe/UniverseAttack.aspx'>Ataque</a></li><li><a href='/es/Universe/Conquer.aspx'>Conquistar</a></li><li><a href='/es/Universe/Raids.aspx'>Saqueo</a></li><li><a href='/es/Universe/UnloadCargo.aspx'>Descargar Carga</a></li><li><a href='/es/Universe/DevastationAttack.aspx'>Ataque Devastación</a></li></ul><h2>Elementos del Universo</h2><ul><li><a href='/es/Universe/Planets.aspx'>Planetas</a></li><li><a href='/es/Universe/WormHole.aspx'>Túnel Espacial</a></li><li><a href='/es/Universe/Fleet.aspx'>Flota</a></li><li><a href='/es/Universe/Arenas.aspx'>Arenas</a></li><li><a href='/es/Universe/Beacon.aspx'>Centinela</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Otros</h2><ul><li><a href='/es/Universe/Alliance.aspx'>Alianza</a></li><li><a href='/es/Universe/Relics.aspx'>Relics</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Ataque Devastación</h1>
	<div class="content">
  <p><a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> is the ultimate weapon of the <a href='/es/Race/DarkHumans.aspx'>Renegados</a>. It gets available when you build the <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> building.</p>
  <p>More buildings of this kind you have, more powerfull the weapon will be. If you upgrade all the devastations on your private zone to level 2, the <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> will be at it's full power.</p>
  <h2>States</h2>
    You can check the state in the upper right corner of the screen. The devastation has 4 states:
    <ul><li><img src="/Resources/Images/en/DevastationNotAvailable.gif" alt="Devastation Not Available" title="Devastation Not Available" /><br />
  The <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> building is not built in any of your private planets.
 </li><li><img src="/Resources/Images/en/DevastationNotReady.gif" alt="Devastation Not Ready" title="Devastation Not Ready" /><br />
  The <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> is built but you don't have enough resouces to fire it.
 </li><li><img src="/Resources/Images/en/DevastationReady.gif" alt="Devastation Ready" title="Devastation Ready" /><br />
  The <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> is built and you can fire it.
 </li><li><img src="/Resources/Images/en/DevastationCooldown.gif" alt="Devastation Cooldown" title="Devastation Cooldown" /><br />
  The <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> was recently fired and it is on a cooldown fase.
 </li></ul><h2>Usage</h2><p>You can use the <a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> from any <a href='/es/Universe/Fleet.aspx'>Flota</a> available in the <a href='/es/Universe/HotZone.aspx'>Zona Pública</a>. Just click on the <a href='/es/Universe/Fleet.aspx'>Flota</a>, them click on the target (can be a <a href='/es/Universe/Fleet.aspx'>Flota</a>, a <a href='/es/Universe/Planets.aspx'>Planeta</a> or an empty region of the <a href='/es/Universe/Default.aspx'>Universo</a>) like in the picture below:</p><img src="/Resources/Images/en/DevastationFire.gif" alt="Devastation Fire" title="Devastation Fire" /><p><a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> has not any range. As long as your target is on a discovered space, you can fire it. Also, be aware!. The <b><a class='devastation' href='/es/Facility/Devastation.aspx'>Devastación</a> affects your <a href='/es/Universe/Fleet.aspx'>Flota</a>s or our allied's <a href='/es/Universe/Fleet.aspx'>Flota</a>s if they are in range</b></p><h1>Levels</h1><ul><li>Level 1 - Destroys 9% of the units of the targeted <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>7000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>7000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>7000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>1000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>1000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>1000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>1000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>1000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 2 - Destroys 18% of the units of the targeted <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>14000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>14000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>14000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>2000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>2000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>2000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>2000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>2000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 3 - Destroys 27% of the units of the targeted <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>21000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>21000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>21000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>3000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>3000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>3000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>3000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>3000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 4 - Destroys 36% of the units of the targeted <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>28000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>28000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>28000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>4000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>4000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>4000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>4000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>4000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 5 - Destroys 45% of the units of the targeted <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>35000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>35000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>35000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>5000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>5000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>5000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>5000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>5000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 6 - Destroys 54% of the units of the affected <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>42000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>42000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>42000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>6000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>6000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>6000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>6000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>6000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 7 - Destroys 63% of the units of the affected <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>49000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>49000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>49000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>7000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>7000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>7000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>7000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>7000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 8 - Destroys 72% of the units of the affected <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>65000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>65000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>65000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>10000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>10000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>10000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>10000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>10000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 9 - Destroys 81% of the units of the affected <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>75000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>75000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>75000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>15000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>15000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>15000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>15000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>15000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 10 - Destroys 90% of the units of the affected <a href='/es/Universe/Fleet.aspx'>Flota</a> or <a href='/es/Universe/Planets.aspx'>Planeta</a>. Affects the target coordinate and all the coordinates in 2 a square distance (a total of 25 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>90000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>90000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>90000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>20000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>20000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>20000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>20000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>20000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>