<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Mobs
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Mobs</h1><p><div class="content">
    Um <u>mob</u> é um inimigo controlado pelo jogo(inteligência artifical). Hás-de encontrar vários mobs a <a href='/pt/Universe/Travel.aspx'>Viajar</a> pelo
    <a href='/pt/Universe/Default.aspx'>Universo</a>. Há inclusivé certas <a href='/pt/Quests.aspx'>Missões</a> em que tens de caçar mobs específicos. As <a href='/pt/UnitIndex.aspx'>Unidades de Combate</a> dos mobs são muito poderosas, e poderás
    obtê-las através de algumas <a href='/pt/Quests.aspx'>Missões</a> ou da <a href='/pt/Commerce/AuctionHouse.aspx'>Casa de Leilões</a>.
  </div></p><table class='table'><tr><th>Raça</td><th>Unidades de Combate</td></tr><tr><td><a href='/pt/Race/Mercs.aspx'>Mercs</a></td><td><ul class='unitIndexList'><li><a href='/pt/Unit/Sentry.aspx'><img class='sentry' src='http://resources.orionsbelt.eu/Images/Common/Units/sentry.png' alt='Vigilante' /></a></li><li><a href='/pt/Unit/Reaper.aspx'><img class='reaper' src='http://resources.orionsbelt.eu/Images/Common/Units/reaper.png' alt='Ceifeiro' /></a></li><li><a href='/pt/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Flagelo' /></a></li><li><a href='/pt/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Caminhante' /></a></li><li><a href='/pt/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titã' /></a></li><li><a href='/pt/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Barba de Prata' /></a></li><li><a href='/pt/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Barba Metálica' /></a></li></ul></td></tr><tr><td>[SpaceForce]</td><td><ul class='unitIndexList'><li><a href='/pt/Unit/Jumper.aspx'><img class='jumper' src='http://resources.orionsbelt.eu/Images/Common/Units/jumper.png' alt='Jumper' /></a></li><li><a href='/pt/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/pt/Unit/Cypher.aspx'><img class='cypher' src='http://resources.orionsbelt.eu/Images/Common/Units/cypher.png' alt='Cypher' /></a></li><li><a href='/pt/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Rastejante' /></a></li><li><a href='/pt/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Punho' /></a></li><li><a href='/pt/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Comandante Raposa' /></a></li><li><a href='/pt/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='Capitão Lobo' /></a></li></ul></td></tr></table>
	
</asp:Content>