<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/fr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Trou stellaire
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Univers</h2><ul><li><a href='/fr/Universe/PrivateZone.aspx'>Zone privée</a></li><li><a href='/fr/Universe/HotZone.aspx'>Zone publique</a></li><li><a href='/fr/Universe/Coordinates.aspx'>Coordonées</a></li></ul><h2>Actions dans l'univers</h2><ul><li><a href='/fr/Universe/Travel.aspx'>Voyage</a></li><li><a href='/fr/Universe/LineOfSight.aspx'>Ligne de vision</a></li><li><a href='/fr/Universe/Colonize.aspx'>Coloniser</a></li><li><a href='/fr/Universe/UniverseAttack.aspx'>Attaque</a></li><li><a href='/fr/Universe/Conquer.aspx'>Conquérir</a></li><li><a href='/fr/Universe/Raids.aspx'>Pillage</a></li><li><a href='/fr/Universe/UnloadCargo.aspx'>Déposer cargainson</a></li><li><a href='/fr/Universe/DevastationAttack.aspx'>Attaque dévastation</a></li></ul><h2>Éléments de l'univers</h2><ul><li><a href='/fr/Universe/Planets.aspx'>Planètes</a></li><li><a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a></li><li><a href='/fr/Universe/Fleet.aspx'>Escadrile</a></li><li><a href='/fr/Universe/Arenas.aspx'>Arenas</a></li><li><a href='/fr/Universe/Beacon.aspx'>Satellite</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Autre</h2><ul><li><a href='/fr/Universe/Alliance.aspx'>Alliance</a></li><li><a href='/fr/Universe/Relics.aspx'>Reliques</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Trou stellaire</h1>
	<div class="content">
  <div style="float:right">
    <img src="/Resources/Images/WormHole.png" alt="Worm Hole" title="Worm Hole" />
  </div>
  <p>The <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> is used to instantaneally transport a <a href='/fr/Universe/Fleet.aspx'>Escadrile</a> from one point of the <a href='/fr/Universe/Default.aspx'>Univers</a> to another.</p>
  <p>In every <a href='/fr/Universe/PrivateZone.aspx'>Zone privée</a> there is a <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> that connects you to the rest of the <a href='/fr/Universe/Default.aspx'>Univers</a>. It is hiddIt is hidden so you have to explorer in order to find it.
    This <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> is also private. This means that you are the only one that can use it. Below is a image of an
    undiscovered <a href='/fr/Universe/PrivateZone.aspx'>Zone privée</a> with the <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a>.</p>
  <img src="/Resources/Images/PrivateWormHole.png" alt="Private Worm Hole" title="Private Worm Hole" />
  <p>To discover a new wormhole you only need to use it. For that, you must click on a <a href='/fr/Universe/Fleet.aspx'>Escadrile</a> and then in the <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a>. 
    When you do this, the folowing popup will appear:</p>
  <img src="/Resources/Images/en/WormHole.png" alt="Worm Hole Popup" title="Worm Hole Popup" />
  <p>When you click transport, a window with all the available <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> will appear.</p>
  <p>This window has 2 tabs:
    <ul><li>Universe <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> - all the public <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> that you have found</li><li>Alliance <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> - all the <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> your alliance (or you) have built (These <a href='/fr/Universe/WormHole.aspx'>Trous stellaire</a> can only be built buy the <a href='/fr/Race/Bugs.aspx'>Levyr</a>. See more information below).</li></ul></p>
  <h1><a href='/fr/Race/Bugs.aspx'>Levyr</a> Wormhole</h1>
  <p>This special kind of <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> is the <a href='/fr/Race/Bugs.aspx'>Levyr</a> ultimate weapon. This <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> can be used only by you and, in higher stages of development, by the members of your alliance.</p>
  <p>
 Each built <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> has a level. Its level is given by the sum of the levels of your <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a>. Example: if you have 3 <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> level 1 and 1 <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> level 2,
 then your <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> level will be 5.
    </p>
  <h1>States</h1>
    You can check the state in the upper right corner of the screen. The <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> has 4 states:
    <ul><li><img src="/Resources/Images/en/WormHoleNotAvailable.gif" alt="WormHole Not Available" title="WormHole Not Available" /><br />
  The <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> is not built in any of your private planets.
 </li><li><img src="/Resources/Images/en/WormHoleNotReady.gif" alt="WormHole Not Ready" title="WormHole Not Ready" /><br />
   The <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> is built but you don't have enough resouces to create it.
  </li><li><img src="/Resources/Images/en/WormHoleReady.gif" alt="WormHole Ready" title="WormHole Ready" /><br />
   The <a class='wormholecreator' href='/fr/Facility/WormHoleCreator.aspx'>Synthétiseur à trou stellaire</a> is built and you can create a <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a>.
  </li><li><img src="/Resources/Images/en/WormHoleCoolDown.gif" alt="WormHole Cooldown" title="WormHole Cooldown" /><br />
   A <a href='/fr/Universe/WormHole.aspx'>Trou stellaire</a> was recently created and it is on a cooldown fase.
  </li></ul><h1>Levels:</h1><ul><li>Level 1 - Duration 1 day. Construction cooldown of 10 days. Only the owner can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>50 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>50 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>50 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>50 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>50 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 2 - Duration 2 days. Construction cooldown of 9 days. Only the owner can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>100 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>100 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>100 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>100 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>100 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 3 - Duration 3 days. Construction cooldown of 8 days. Only the owner can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>150 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>150 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>150 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>150 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>150 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 4 - Duration 4 days. Construction cooldown of 7 days. Only the owner and players of the same alliance and from the <a href='/fr/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>200 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>200 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>200 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>200 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>200 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 5 - Duration 5 days. Construction cooldown of 6 days. Only the owner and players of the same alliance and from the <a href='/fr/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>100 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>100 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>250 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>250 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>250 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>250 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>250 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 6 - Duration 6 days. Construction cooldown of 5 days. Only the owner and players of the same alliance and from the <a href='/fr/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>300 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>300 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>300 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>300 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>300 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 7 - Duration 7 days. Construction cooldown of 4 days. Only the owner and players of the same alliance and from the <a href='/fr/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>350 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>350 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>350 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>350 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>350 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 8 - Duration 8 days. Construction cooldown of 3 days. Only the owner and players of the same alliance and from thee <a href='/fr/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>400 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>400 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>400 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>400 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>400 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 9 - Duration 9 days. Construction cooldown of 2 days. Only the owner and players of the same alliance (with Level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>450 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>450 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>450 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>450 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>450 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 10 - Duration 10 days. Construction cooldown of 1 days. Only the owner and players of the same alliance (with Level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>2000 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>2000 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>500 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>500 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>500 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>500 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>500 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>