//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace OrionsBelt.WebUserInterface.PaysafeWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaysafeProxySoap", Namespace="http://tempuri.org/")]
    public partial class PaysafeProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreatePostOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaymentVerificationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeDebitOperationCompleted;
        
        private System.Threading.SendOrPostCallback PaypalVerificationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaysafeProxy() {
            this.Url = global::OrionsBelt.WebUserInterface.Properties.Settings.Default.OrionsBelt_WebUserInterface_PaysafeWS_PaysafeProxy;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreatePostCompletedEventHandler CreatePostCompleted;
        
        /// <remarks/>
        public event PaymentVerificationCompletedEventHandler PaymentVerificationCompleted;
        
        /// <remarks/>
        public event MakeDebitCompletedEventHandler MakeDebitCompleted;
        
        /// <remarks/>
        public event PaypalVerificationCompletedEventHandler PaypalVerificationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreatePost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreatePost(double cost, int principalId, string principalLang, string basePath) {
            object[] results = this.Invoke("CreatePost", new object[] {
                        cost,
                        principalId,
                        principalLang,
                        basePath});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreatePostAsync(double cost, int principalId, string principalLang, string basePath) {
            this.CreatePostAsync(cost, principalId, principalLang, basePath, null);
        }
        
        /// <remarks/>
        public void CreatePostAsync(double cost, int principalId, string principalLang, string basePath, object userState) {
            if ((this.CreatePostOperationCompleted == null)) {
                this.CreatePostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreatePostOperationCompleted);
            }
            this.InvokeAsync("CreatePost", new object[] {
                        cost,
                        principalId,
                        principalLang,
                        basePath}, this.CreatePostOperationCompleted, userState);
        }
        
        private void OnCreatePostOperationCompleted(object arg) {
            if ((this.CreatePostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreatePostCompleted(this, new CreatePostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaymentVerification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DispositionData PaymentVerification(string mtid) {
            object[] results = this.Invoke("PaymentVerification", new object[] {
                        mtid});
            return ((DispositionData)(results[0]));
        }
        
        /// <remarks/>
        public void PaymentVerificationAsync(string mtid) {
            this.PaymentVerificationAsync(mtid, null);
        }
        
        /// <remarks/>
        public void PaymentVerificationAsync(string mtid, object userState) {
            if ((this.PaymentVerificationOperationCompleted == null)) {
                this.PaymentVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaymentVerificationOperationCompleted);
            }
            this.InvokeAsync("PaymentVerification", new object[] {
                        mtid}, this.PaymentVerificationOperationCompleted, userState);
        }
        
        private void OnPaymentVerificationOperationCompleted(object arg) {
            if ((this.PaymentVerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaymentVerificationCompleted(this, new PaymentVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MakeDebit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void MakeDebit(string mtid, string amount, string currency) {
            this.Invoke("MakeDebit", new object[] {
                        mtid,
                        amount,
                        currency});
        }
        
        /// <remarks/>
        public void MakeDebitAsync(string mtid, string amount, string currency) {
            this.MakeDebitAsync(mtid, amount, currency, null);
        }
        
        /// <remarks/>
        public void MakeDebitAsync(string mtid, string amount, string currency, object userState) {
            if ((this.MakeDebitOperationCompleted == null)) {
                this.MakeDebitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeDebitOperationCompleted);
            }
            this.InvokeAsync("MakeDebit", new object[] {
                        mtid,
                        amount,
                        currency}, this.MakeDebitOperationCompleted, userState);
        }
        
        private void OnMakeDebitOperationCompleted(object arg) {
            if ((this.MakeDebitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeDebitCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PaypalVerification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VerifyResult PaypalVerification(string url, string message) {
            object[] results = this.Invoke("PaypalVerification", new object[] {
                        url,
                        message});
            return ((VerifyResult)(results[0]));
        }
        
        /// <remarks/>
        public void PaypalVerificationAsync(string url, string message) {
            this.PaypalVerificationAsync(url, message, null);
        }
        
        /// <remarks/>
        public void PaypalVerificationAsync(string url, string message, object userState) {
            if ((this.PaypalVerificationOperationCompleted == null)) {
                this.PaypalVerificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPaypalVerificationOperationCompleted);
            }
            this.InvokeAsync("PaypalVerification", new object[] {
                        url,
                        message}, this.PaypalVerificationOperationCompleted, userState);
        }
        
        private void OnPaypalVerificationOperationCompleted(object arg) {
            if ((this.PaypalVerificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PaypalVerificationCompleted(this, new PaypalVerificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DispositionData {
        
        private string amountField;
        
        private string currencyField;
        
        private DispositionState stateField;
        
        private string serialsField;
        
        /// <remarks/>
        public string amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public DispositionState state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string serials {
            get {
                return this.serialsField;
            }
            set {
                this.serialsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum DispositionState {
        
        /// <remarks/>
        Created,
        
        /// <remarks/>
        Disposed,
        
        /// <remarks/>
        Expired,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyResult {
        
        private string resultField;
        
        private bool successField;
        
        /// <remarks/>
        public string result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreatePostCompletedEventHandler(object sender, CreatePostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreatePostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreatePostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PaymentVerificationCompletedEventHandler(object sender, PaymentVerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaymentVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaymentVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DispositionData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DispositionData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MakeDebitCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void PaypalVerificationCompletedEventHandler(object sender, PaypalVerificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PaypalVerificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PaypalVerificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VerifyResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VerifyResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591