<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/hr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Zraka
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Svemir</h2><ul><li><a href='/hr/Universe/PrivateZone.aspx'>Privatna Zona</a></li><li><a href='/hr/Universe/HotZone.aspx'>Hot Zone</a></li><li><a href='/hr/Universe/Coordinates.aspx'>Koordinate</a></li></ul><h2>Akcije Svemira</h2><ul><li><a href='/hr/Universe/Travel.aspx'>Putovanje</a></li><li><a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a></li><li><a href='/hr/Universe/Colonize.aspx'>Koloniziraj</a></li><li><a href='/hr/Universe/UniverseAttack.aspx'>Napad</a></li><li><a href='/hr/Universe/Conquer.aspx'>Pokori</a></li><li><a href='/hr/Universe/Raids.aspx'>Pljačka</a></li><li><a href='/hr/Universe/UnloadCargo.aspx'>Istovari Teret</a></li><li><a href='/hr/Universe/DevastationAttack.aspx'>Napad Devastacije</a></li></ul><h2>Elementi Svemira</h2><ul><li><a href='/hr/Universe/Planets.aspx'>Planeti</a></li><li><a href='/hr/Universe/WormHole.aspx'>Crvotočina</a></li><li><a href='/hr/Universe/Fleet.aspx'>Flota</a></li><li><a href='/hr/Universe/Arenas.aspx'>Arene</a></li><li><a href='/hr/Universe/Beacon.aspx'>Zraka</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Drugi</h2><ul><li><a href='/hr/Universe/Alliance.aspx'>Savez</a></li><li><a href='/hr/Universe/Relics.aspx'>Relikvije</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Zraka</h1>
	<div class="content">
  <img src="/Resources/Images/BeaconImg.png" style="float:right;" alt="Beacon" />
  <p><a href='/hr/Universe/Beacon.aspx'>Zraka</a> je <a href='/hr/Race/LightHumans.aspx'>Utopians</a> Ultimativno Oružje. Kako ime nagovješta, to je nešto što će patrolirati određenom regijom svemira. I to je točno to.</p>
  <p>Kada smjestite <a href='/hr/Universe/Beacon.aspx'>Zraka</a> ona će ovisno o nivou dati informacije o okolnim <a href='/hr/Universe/Planets.aspx'>Planet</a> i <a href='/hr/Universe/Fleet.aspx'>Flota</a>.</p>
  <p>Njezin nivo je dan sa zbrojem nivoa vašega <a class='deepspacescanner' href='/hr/Facility/DeepSpaceScanner.aspx'>Skener Dubokog Svemira</a>. Primjer: ako imate 3 <a class='deepspacescanner' href='/hr/Facility/DeepSpaceScanner.aspx'>Skener Dubokog Svemira</a> nivo 1 i 1 <a class='deepspacescanner' href='/hr/Facility/DeepSpaceScanner.aspx'>Skener Dubokog Svemira</a> nivo 2, tada će vaš <a href='/hr/Universe/Beacon.aspx'>Zraka</a> nivo biti 5.</p>
  <h2>Kako je Stvoriti</h2>
  <p>Beacon može biti stvorena od bilo koje flote. Ako su svi uvjeti ispunjeni (potrebni reusrsi i ovisno o nivou jeste li blizu planeta kojega posjedujete), sljedeća mogućnost će se pojaviti u 
popup-u flote:</p>
  <img src="/Resources/Images/BeaconUsage.png" style="float:right;" alt="Beacon" />
  <h1>Stanja</h1>
Možete provjeriti stanje u gornjem desnom kutu ekrana. Kreacija Zrake ima 4 stanja:
<ul><li><img src="/Resources/Images/en/BeaconNotAvailable.gif" alt="Beacon Not Available" title="Beacon Not Available" /><br />
[DeepSpaceScanner nije izgrađen an nijednom od vaših privatnih planeta.
</li><li><img src="/Resources/Images/en/BeaconNotReady.gif" alt="Beacon Not Ready" title="Beacon Not Ready" /><br />
<a class='deepspacescanner' href='/hr/Facility/DeepSpaceScanner.aspx'>Skener Dubokog Svemira</a> je izgrađen ali nema dovoljno reusrsa da se stvori <a href='/hr/Universe/Beacon.aspx'>Zraka</a>.
</li><li><img src="/Resources/Images/en/BeaconReady.gif" alt="Beacon Ready" title="Beacon Ready" /><br />
<a class='deepspacescanner' href='/hr/Facility/DeepSpaceScanner.aspx'>Skener Dubokog Svemira</a> je izgrađen i možete stvoriti <a href='/hr/Universe/Beacon.aspx'>Zraka</a>.
</li><li><img src="/Resources/Images/en/BeaconCooldown.gif" alt="Beacon Cooldown" title="Beacon Cooldown" /><br />
<a href='/hr/Universe/Beacon.aspx'>Zraka</a> je nedavno upotrijebljena i sada je u fazi hlađenja.
</li></ul><h1>Levels</h1><ul><li>Level 1 - You can see how much <a href='/hr/Battles/Light.aspx'>Lagani</a> units a <a href='/hr/Universe/Fleet.aspx'>Flota</a> has. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 2 sectors all around. Cooldown takes 10 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>300 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>300 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>300 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>60 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>60 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>60 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>60 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>60 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 2 - You can see how much <a href='/hr/Battles/Light.aspx'>Lagani</a> and <a href='/hr/Battles/Medium.aspx'>Srednji</a> units a <a href='/hr/Universe/Fleet.aspx'>Flota</a> has. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 2 sectors all around. Cooldown takes 9 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>600 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>600 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>600 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>120 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>120 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>120 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>120 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>120 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 3 - You can see how much <a href='/hr/Battles/Light.aspx'>Lagani</a>, <a href='/hr/Battles/Medium.aspx'>Srednji</a> and <a href='/hr/Battles/Heavy.aspx'>Teški</a> units a <a href='/hr/Universe/Fleet.aspx'>Flota</a> has. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 2 sectors all around. Cooldown takes 8 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>900 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>900 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>900 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>180 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>180 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>180 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>180 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>180 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 4 - You can see the type and quantity of each <a href='/hr/Battles/Light.aspx'>Lagani</a> in a <a href='/hr/Universe/Fleet.aspx'>Flota</a> (has well has the quantity of <a href='/hr/Battles/Medium.aspx'>Srednji</a> and <a href='/hr/Battles/Heavy.aspx'>Teški</a> units). <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 3 sectors all around. Cooldown takes 7 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>1200 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1200 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1200 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>240 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>240 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>240 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>240 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>240 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 5 - You can see the type and quantity of each <a href='/hr/Battles/Light.aspx'>Lagani</a> and <a href='/hr/Battles/Medium.aspx'>Srednji</a> in a <a href='/hr/Universe/Fleet.aspx'>Flota</a> (has well has the quantity of <a href='/hr/Battles/Heavy.aspx'>Teški</a> units). <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 3 sectors all around. Cooldown takes 6 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>1500 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1500 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1500 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>300 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>300 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>300 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>300 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>300 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 6 - You can see the type and quantity of each <a href='/hr/Battles/Light.aspx'>Lagani</a>, <a href='/hr/Battles/Medium.aspx'>Srednji</a> and <a href='/hr/Battles/Heavy.aspx'>Teški</a> in a <a href='/hr/Universe/Fleet.aspx'>Flota</a>. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 3 sectors all around. Cooldown takes 5 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>1800 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1800 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1800 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>360 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>360 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>360 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>360 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>360 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 7 - You can see the level of the buildings in a <a href='/hr/Universe/Planets.aspx'>Planet</a>. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 4 sectors all around. Cooldown takes 4 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>2100 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2100 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2100 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>420 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>420 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>420 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>420 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>420 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 8 - You can see the income of the <a href='/hr/Universe/Planets.aspx'>Planet</a>. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 4 sectors all around. Cooldown takes 3 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>2400 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2400 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2400 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>480 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>480 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>480 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>480 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>480 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 9 - You can see the defense <a href='/hr/Universe/Fleet.aspx'>Flota</a> of a <a href='/hr/Universe/Planets.aspx'>Planet</a>. <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> is 4 sectors all around. Cooldown takes 2 turns.<br />
 Cost: <div id="resourcesCost"><ul><li>2700 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2700 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2700 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>540 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>540 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>540 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>540 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>540 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 10 - <a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a> of 5 sectors all around. Cooldown takes 1 turn.<br />
 Cost: <div id="resourcesCost"><ul><li>3000 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>3000 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>3000 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>600 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>600 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>600 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>600 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>600 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul><p>The picture below illustrates the information of all the levels:</p><img src="/Resources/Images/Beacon.png" alt="Beacon" title="Beacon" /></div>
</asp:Content>