<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/hr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Napad Devastacije
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Svemir</h2><ul><li><a href='/hr/Universe/PrivateZone.aspx'>Privatna Zona</a></li><li><a href='/hr/Universe/HotZone.aspx'>Hot Zone</a></li><li><a href='/hr/Universe/Coordinates.aspx'>Koordinate</a></li></ul><h2>Akcije Svemira</h2><ul><li><a href='/hr/Universe/Travel.aspx'>Putovanje</a></li><li><a href='/hr/Universe/LineOfSight.aspx'>Linija Vidika</a></li><li><a href='/hr/Universe/Colonize.aspx'>Koloniziraj</a></li><li><a href='/hr/Universe/UniverseAttack.aspx'>Napad</a></li><li><a href='/hr/Universe/Conquer.aspx'>Pokori</a></li><li><a href='/hr/Universe/Raids.aspx'>Pljačka</a></li><li><a href='/hr/Universe/UnloadCargo.aspx'>Istovari Teret</a></li><li><a href='/hr/Universe/DevastationAttack.aspx'>Napad Devastacije</a></li></ul><h2>Elementi Svemira</h2><ul><li><a href='/hr/Universe/Planets.aspx'>Planeti</a></li><li><a href='/hr/Universe/WormHole.aspx'>Crvotočina</a></li><li><a href='/hr/Universe/Fleet.aspx'>Flota</a></li><li><a href='/hr/Universe/Arenas.aspx'>Arene</a></li><li><a href='/hr/Universe/Beacon.aspx'>Zraka</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Drugi</h2><ul><li><a href='/hr/Universe/Alliance.aspx'>Savez</a></li><li><a href='/hr/Universe/Relics.aspx'>Relikvije</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Napad Devastacije</h1>
	<div class="content">
  <p><a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> je ultimativno oružje <a href='/hr/Race/DarkHumans.aspx'>Renegades</a>. Postaje dostupno kada izgradite <a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> zgradu.</p>
  <p>Što imate više zgrada ovoga tipa to će moćnije oružje biti.
Ako unaprijedite sve devastacije na planetima unutar vaše privatne zone na nivo 2, <a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> će biti na punoj snazi.</p>
  <h2>States</h2>
Možete provjeriti stanje u gornjem desnom kutu ekrana. Devastacija ima 4 stanja:
<ul><li><img src="/Resources/Images/en/DevastationNotAvailable.gif" alt="Devastation Not Available" title="Devastation Not Available" /><br />
<a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> zgrada nije izgrađena na niti jednom od vaših privatnih planeta.
</li><li><img src="/Resources/Images/en/DevastationNotReady.gif" alt="Devastation Not Ready" title="Devastation Not Ready" /><br />
<a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> je izgrađena ali nemate dovoljno resursa da je opalite.
 </li><li><img src="/Resources/Images/en/DevastationReady.gif" alt="Devastation Ready" title="Devastation Ready" /><br />
<a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> je izgrađena i imate dovoljno resursa da je opalite.
 </li><li><img src="/Resources/Images/en/DevastationCooldown.gif" alt="Devastation Cooldown" title="Devastation Cooldown" /><br />
<a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> je nedavno opaljena i trenutno je u fazi hlađenja.
 </li></ul><h2>Usage</h2><p>Možete upotrijebiti <a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> iz bilo koje <a href='/hr/Universe/Fleet.aspx'>Flota</a> dostupne u <a href='/hr/Universe/HotZone.aspx'>Hot Zone</a>. Samo kliknite na  <a href='/hr/Universe/Fleet.aspx'>Flota</a>, tada kliknite na metu (može biti <a href='/hr/Universe/Fleet.aspx'>Flota</a>,  <a href='/hr/Universe/Planets.aspx'>Planet</a> ili prazna regija u <a href='/hr/Universe/Default.aspx'>Svemir</a>)kao na slici ispod:</p><img src="/Resources/Images/en/DevastationFire.gif" alt="Devastation Fire" title="Devastation Fire" /><p><a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> nema dometa. DOk god je vaša meta u otkrivenom svemiru, možete je opaliti. Također, čuvajte se!. <b><a class='devastation' href='/hr/Facility/Devastation.aspx'>Devastacija</a> utječe na vaše <a href='/hr/Universe/Fleet.aspx'>Flota</a>s ili na savezničke  <a href='/hr/Universe/Fleet.aspx'>Flota</a>s ako su unutar dometa</b></p><h1>Nivoi</h1><ul><li>Level 1 - Uništava 9% ciljanih jednica <a href='/hr/Universe/Fleet.aspx'>Flota</a> ili <a href='/hr/Universe/Planets.aspx'>Planet</a>. Utječe samo na jedne koordinate.<br />
Custo: <div id="resourcesCost"><ul><li>7000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>7000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>7000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>1000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>1000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>1000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>1000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>1000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 2 - Destroys 18% of the units of the targeted <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>14000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>14000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>14000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>2000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>2000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>2000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>2000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>2000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 3 - Destroys 27% of the units of the targeted <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>21000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>21000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>21000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>3000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>3000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>3000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>3000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>3000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 4 - Destroys 36% of the units of the targeted <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>28000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>28000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>28000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>4000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>4000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>4000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>4000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>4000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 5 - Destroys 45% of the units of the targeted <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Only affects one coordinate.<br />
 Custo: <div id="resourcesCost"><ul><li>35000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>35000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>35000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>5000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>5000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>5000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>5000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>5000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 6 - Destroys 54% of the units of the affected <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>42000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>42000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>42000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>6000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>6000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>6000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>6000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>6000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 7 - Destroys 63% of the units of the affected <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>49000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>49000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>49000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>7000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>7000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>7000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>7000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>7000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 8 - Destroys 72% of the units of the affected <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>65000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>65000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>65000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>10000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>10000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>10000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>10000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>10000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 9 - Destroys 81% of the units of the affected <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Affects the target coordinate and all the coordinates surrounding it (a total of 9 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>75000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>75000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>75000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>15000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>15000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>15000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>15000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>15000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 10 - Destroys 90% of the units of the affected <a href='/hr/Universe/Fleet.aspx'>Flota</a> or <a href='/hr/Universe/Planets.aspx'>Planet</a>. Affects the target coordinate and all the coordinates in 2 a square distance (a total of 25 coordinates).<br />
 Custo: <div id="resourcesCost"><ul><li>90000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>90000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>90000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>20000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>20000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>20000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>20000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>20000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>