//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionsBelt.WebUserInterface.Controls.Generic {
    
    
    /// <summary>
    /// PrivateBoardSender class.
    /// </summary>
    /// <remarks>
    /// Auto-generated class.
    /// </remarks>
    public partial class PrivateBoardSender {
        
        /// <summary>
        /// pbEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebComponents.Controls.PrivateBoardEditor pbEditor;
        
        /// <summary>
        /// defaults control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebUserInterface.Controls.PrivateBoardDefaultsEditor defaults;
        
        
    }
}
