<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Grande Porte
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Conceitos de Batalha</h2><ul><li><a href='/pt/Battles/GameBoard.aspx'>Tabuleiro de Jogo</a></li><li><a href='/pt/Battles/Deploy.aspx'>Posicionar</a></li><li><a href='/pt/Battles/Movement.aspx'>Movimento</a></li><li><a href='/pt/Battles/Rules.aspx'>Regras</a></li></ul><h2>Ataque</h2><ul><li><a href='/pt/Battles/Range.aspx'>Alcance</a></li><li><a href='/pt/Battles/Catapult.aspx'>Catapulta</a></li><li><a href='/pt/Battles/ParalyseAttack.aspx'>Ataque Paralizador</a></li><li><a href='/pt/Battles/Replicator.aspx'>Replicador</a></li><li><a href='/pt/Battles/StrikeBack.aspx'>Contra-Ataque</a></li><li><a href='/pt/Battles/InfestationAttack.aspx'>Ataque Venenoso</a></li><li><a href='/pt/Battles/RemoveAbilityAttack.aspx'>Remoção de Habilidades</a></li><li><a href='/pt/Battles/TripleAttack.aspx'>Ataque Triplo</a></li><li><a href='/pt/Battles/BombAttack.aspx'>Ataque Bomba</a></li><li><a href='/pt/Battles/Rebound.aspx'>Ricochete</a></li></ul><h2>Categoria</h2><ul><li><a href='/pt/Battles/Light.aspx'>Pequeno Porte</a></li><li><a href='/pt/Battles/Medium.aspx'>Médio Porte</a></li><li><a href='/pt/Battles/Heavy.aspx'>Grande Porte</a></li><li><a href='/pt/Battles/Ultimate.aspx'>Suprema</a></li><li><a href='/pt/Battles/Special.aspx'>Especial</a></li></ul><h2>Tipo de Batalha</h2><ul><li><a href='/pt/Battles/TotalAnnihilation.aspx'>Destruição Total</a></li><li><a href='/pt/Battles/Regicide.aspx'>Regicídeo</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Unidades de Grande Porte</h1>
<div class="content">
    As unidades de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> simbolizam o poder de ataque. São as <a href='/pt/UnitIndex.aspx'>Unidades de Combate</a> mais poderosas, quer em ataque, quer
    em defesa, sendo somente limitadas pelo tipo de <a href='/pt/Battles/Movement.aspx'>Movimento</a> e <a href='/pt/Battles/Movement.aspx#MovCost'>Custo de Movimento</a>. As unidades de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> também
    são conhecidas pelo seu longo <a href='/pt/Battles/Range.aspx'>Alcance</a>.
    <p />
    Naturalmente temos <a href='/pt/UnitIndex.aspx'>Unidades de Combate</a> de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> que não seguem exactamente este padrão. Por exemplo a <a class='doomer' href='/pt/Unit/Doomer.aspx'>Aniquiladora</a>,
    a <a class='blackwidow' href='/pt/Unit/BlackWidow.aspx'>Viúva Negra</a> e o <a class='taurus' href='/pt/Unit/Taurus.aspx'>Touro</a> só têm 3 de <a href='/pt/Battles/Range.aspx'>Alcance</a>, mas são compensados por mais liberdade de <a href='/pt/Battles/Movement.aspx'>Movimento</a>,
    ou por poder extra.
    <p />
    As unidades de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> têm de ter especial atenção à <a class='rain' href='/pt/Unit/Rain.aspx'>Rain</a> e à <a class='darkrain' href='/pt/Unit/DarkRain.aspx'>Rain Sombria</a>, que têm bónus especial de ataque.
    <p />
    Lista de unidades de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a>:
  </div>
	<ul class='imageList'><li><a href='/pt/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Punho' /></a></li><li><a href='/pt/Unit/Nova.aspx'><img class='nova' src='http://resources.orionsbelt.eu/Images/Common/Units/nova.png' alt='Nova' /></a></li><li><a href='/pt/Unit/HiveKing.aspx'><img class='hiveking' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveking.png' alt='Rei da Colmeia' /></a></li><li><a href='/pt/Unit/Bozer.aspx'><img class='bozer' src='http://resources.orionsbelt.eu/Images/Common/Units/bozer.png' alt='Bozer' /></a></li><li><a href='/pt/Unit/Doomer.aspx'><img class='doomer' src='http://resources.orionsbelt.eu/Images/Common/Units/doomer.png' alt='Aniquiladora' /></a></li><li><a href='/pt/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titã' /></a></li><li><a href='/pt/Unit/BlackWidow.aspx'><img class='blackwidow' src='http://resources.orionsbelt.eu/Images/Common/Units/blackwidow.png' alt='Viúva Negra' /></a></li><li><a href='/pt/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='Capitão Lobo' /></a></li><li><a href='/pt/Unit/Fenix.aspx'><img class='fenix' src='http://resources.orionsbelt.eu/Images/Common/Units/fenix.png' alt='Fénix' /></a></li><li><a href='/pt/Unit/Taurus.aspx'><img class='taurus' src='http://resources.orionsbelt.eu/Images/Common/Units/taurus.png' alt='Touro' /></a></li><li><a href='/pt/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Comandante Raposa' /></a></li><li><a href='/pt/Unit/HeavySeeker.aspx'><img class='heavyseeker' src='http://resources.orionsbelt.eu/Images/Common/Units/heavyseeker.png' alt='Mega Batedor' /></a></li><li><a href='/pt/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Barba de Prata' /></a></li><li><a href='/pt/Unit/DarkTaurus.aspx'><img class='darktaurus' src='http://resources.orionsbelt.eu/Images/Common/Units/darktaurus.png' alt='Touro Sombrio' /></a></li><li><a href='/pt/Unit/DarkCrusader.aspx'><img class='darkcrusader' src='http://resources.orionsbelt.eu/Images/Common/Units/darkcrusader.png' alt='Cruzador Sombrio' /></a></li><li><a href='/pt/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Barba Metálica' /></a></li><li><a href='/pt/Unit/Crusader.aspx'><img class='crusader' src='http://resources.orionsbelt.eu/Images/Common/Units/crusader.png' alt='Crusador' /></a></li></ul>
	
</asp:Content>