<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Médio Porte
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Conceitos de Batalha</h2><ul><li><a href='/pt/Battles/GameBoard.aspx'>Tabuleiro de Jogo</a></li><li><a href='/pt/Battles/Deploy.aspx'>Posicionar</a></li><li><a href='/pt/Battles/Movement.aspx'>Movimento</a></li><li><a href='/pt/Battles/Rules.aspx'>Regras</a></li></ul><h2>Ataque</h2><ul><li><a href='/pt/Battles/Range.aspx'>Alcance</a></li><li><a href='/pt/Battles/Catapult.aspx'>Catapulta</a></li><li><a href='/pt/Battles/ParalyseAttack.aspx'>Ataque Paralizador</a></li><li><a href='/pt/Battles/Replicator.aspx'>Replicador</a></li><li><a href='/pt/Battles/StrikeBack.aspx'>Contra-Ataque</a></li><li><a href='/pt/Battles/InfestationAttack.aspx'>Ataque Venenoso</a></li><li><a href='/pt/Battles/RemoveAbilityAttack.aspx'>Remoção de Habilidades</a></li><li><a href='/pt/Battles/TripleAttack.aspx'>Ataque Triplo</a></li><li><a href='/pt/Battles/BombAttack.aspx'>Ataque Bomba</a></li><li><a href='/pt/Battles/Rebound.aspx'>Ricochete</a></li></ul><h2>Categoria</h2><ul><li><a href='/pt/Battles/Light.aspx'>Pequeno Porte</a></li><li><a href='/pt/Battles/Medium.aspx'>Médio Porte</a></li><li><a href='/pt/Battles/Heavy.aspx'>Grande Porte</a></li><li><a href='/pt/Battles/Ultimate.aspx'>Suprema</a></li><li><a href='/pt/Battles/Special.aspx'>Especial</a></li></ul><h2>Tipo de Batalha</h2><ul><li><a href='/pt/Battles/TotalAnnihilation.aspx'>Destruição Total</a></li><li><a href='/pt/Battles/Regicide.aspx'>Regicídeo</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Unidades de Médio Porte</h1>
<div class="content">
    As unidades de <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> são categorizadas por serem as mais equilibradas do jogo. Não são as mais rápidas,
    nem as mais lentas, não são as mais fortes nem as mais fracas. Este equilíbrio de força e liberdade de 
    <a href='/pt/Battles/Movement.aspx'>Movimento</a> faz com que as unidades de <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> sejam o coração de qualquer <a href='/pt/Universe/Fleet.aspx'>Armada</a>.
    <p />
    Apesar de mais fracas que as unidades de <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a>, muitas vezes a sua mobilidade extra, aliada a alguma
    <a href='/pt/Battles/DispensableUnits.aspx'>Carne para Canhão</a> faz com que levem a melhor. Como inimigas naturais, as unidades de <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> têm de
    ter especial atenção à <a class='kamikaze' href='/pt/Unit/Kamikaze.aspx'>Suicida</a> e ao <a class='seeker' href='/pt/Unit/Seeker.aspx'>Batedor</a>.
    <p />
    Lista de unidades de <a href='/pt/Battles/Medium.aspx'>Médio Porte</a>:
  </div>
	<ul class='imageList'><li><a href='/pt/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Suicida' /></a></li><li><a href='/pt/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Aranha' /></a></li><li><a href='/pt/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='Protector da Colmeia' /></a></li><li><a href='/pt/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Perfurador' /></a></li><li><a href='/pt/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vector' /></a></li><li><a href='/pt/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Minhoca' /></a></li><li><a href='/pt/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Flagelo' /></a></li><li><a href='/pt/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/pt/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Escaravelho' /></a></li><li><a href='/pt/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Águia' /></a></li><li><a href='/pt/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Pretoriana' /></a></li><li><a href='/pt/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Ferrão' /></a></li><li><a href='/pt/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/pt/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Destruidor' /></a></li><li><a href='/pt/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/pt/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Rastejante' /></a></li><li><a href='/pt/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Caminhante' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Ataque',Defense:'Defesa',MovementCost:'Custo Movimento',Range:'Alcance',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Comandante Raposa'},HiveProtector:{Name:'Protector da Colmeia'},Doomer:{Name:'Aniquiladora'},Cypher:{Name:'Cypher'},Stinger:{Name:'Ferrão'},CaptainWolf:{Name:'Capitão Lobo'},Destroyer:{Name:'Destruidor'},Myst:{Name:'Myst'},Scarab:{Name:'Escaravelho'},Toxic:{Name:'Tóxica'},Fist:{Name:'Punho'},Flag:{Name:'Bandeira'},DarkTaurus:{Name:'Touro Sombrio'},Egg:{Name:'Ovo'},Jumper:{Name:'Jumper'},BattleMoon:{Name:'Lua de Batalha'},MetallicBeard:{Name:'Barba Metálica'},DarkCrusader:{Name:'Cruzador Sombrio'},Scourge:{Name:'Flagelo'},Crawler:{Name:'Rastejante'},Rain:{Name:'Rain'},Samurai:{Name:'Samurai'},Panther:{Name:'Pantera'},Queen:{Name:'Rainha'},DarkRain:{Name:'Rain Sombria'},Worm:{Name:'Minhoca'},Taurus:{Name:'Touro'},Kamikaze:{Name:'Suicida'},Pretorian:{Name:'Pretoriana'},Seeker:{Name:'Batedor'},Nova:{Name:'Nova'},Maggot:{Name:'Larva'},BlackWidow:{Name:'Viúva Negra'},Crusader:{Name:'Crusador'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Rei da Colmeia'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Perfurador'},Eagle:{Name:'Águia'},Blinker:{Name:'Pisca-pisca'},Sentry:{Name:'Vigilante'},Vector:{Name:'Vector'},Walker:{Name:'Caminhante'},Titan:{Name:'Titã'},SilverBeard:{Name:'Barba de Prata'},Fenix:{Name:'Fénix'},Interceptor:{Name:'Interceptador'},Reaper:{Name:'Ceifeiro'},Raptor:{Name:'Raptor'},Spider:{Name:'Aranha'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Mega Batedor'}};</script>
	
</asp:Content>