<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/en/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Medium
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Battle Concepts</h2><ul><li><a href='/en/Battles/GameBoard.aspx'>Game Board</a></li><li><a href='/en/Battles/Deploy.aspx'>Deploy</a></li><li><a href='/en/Battles/Movement.aspx'>Movement</a></li><li><a href='/en/Battles/Rules.aspx'>Rules</a></li></ul><h2>Attack</h2><ul><li><a href='/en/Battles/Range.aspx'>Range</a></li><li><a href='/en/Battles/Catapult.aspx'>Catapult</a></li><li><a href='/en/Battles/ParalyseAttack.aspx'>Paralyse Attack</a></li><li><a href='/en/Battles/Replicator.aspx'>Replicator</a></li><li><a href='/en/Battles/StrikeBack.aspx'>Strike Back</a></li><li><a href='/en/Battles/InfestationAttack.aspx'>Infestation Attack</a></li><li><a href='/en/Battles/RemoveAbilityAttack.aspx'>Remove Ability Attack</a></li><li><a href='/en/Battles/TripleAttack.aspx'>Triple Attack</a></li><li><a href='/en/Battles/BombAttack.aspx'>Bomb Attack</a></li><li><a href='/en/Battles/Rebound.aspx'>Rebound</a></li></ul><h2>Category</h2><ul><li><a href='/en/Battles/Light.aspx'>Light</a></li><li><a href='/en/Battles/Medium.aspx'>Medium</a></li><li><a href='/en/Battles/Heavy.aspx'>Heavy</a></li><li><a href='/en/Battles/Ultimate.aspx'>Ultimate</a></li><li><a href='/en/Battles/Special.aspx'>Special</a></li></ul><h2>Battle Type</h2><ul><li><a href='/en/Battles/TotalAnnihilation.aspx'>Total Annihilation</a></li><li><a href='/en/Battles/Regicide.aspx'>Regicide</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Medium Units</h1>
<div class="content">
    <a href='/en/Battles/Medium.aspx'>Medium</a> units are known for being the most balanced ones on the game. They aren't the fastest, nor are
    they the slowest. They aren't the strongest, but they aren't the weakest. This balance of force and liberty
    of <a href='/en/Battles/Movement.aspx'>Movement</a> makes <a href='/en/Battles/Medium.aspx'>Medium</a> units the heart of any <a href='/en/Universe/Fleet.aspx'>Fleet</a>.
    <p />
    <a href='/en/Battles/Medium.aspx'>Medium</a> units may be weaker thatn <a href='/en/Battles/Heavy.aspx'>Heavy</a> units, but may times the extra mobility with some help from
    <a href='/en/Battles/DispensableUnits.aspx'>Cannon Fodder</a> turns them into winners. As natural enemies, <a href='/en/Battles/Medium.aspx'>Medium</a> units should avoid the
    <a class='kamikaze' href='/en/Unit/Kamikaze.aspx'>Kamikaze</a> and the <a class='seeker' href='/en/Unit/Seeker.aspx'>Seeker</a>.
    <p />
    <a href='/en/Battles/Medium.aspx'>Medium</a> units:
  </div>
	<ul class='imageList'><li><a href='/en/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Kamikaze' /></a></li><li><a href='/en/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Spider' /></a></li><li><a href='/en/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='Hive Protector' /></a></li><li><a href='/en/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Driller' /></a></li><li><a href='/en/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vector' /></a></li><li><a href='/en/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Worm' /></a></li><li><a href='/en/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Scourge' /></a></li><li><a href='/en/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/en/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Scarab' /></a></li><li><a href='/en/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Eagle' /></a></li><li><a href='/en/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Praetorian' /></a></li><li><a href='/en/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Stinger' /></a></li><li><a href='/en/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/en/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Destroyer' /></a></li><li><a href='/en/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/en/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/en/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Attack',Defense:'Defense',MovementCost:'Movement Cost',Range:'Range',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Commander Fox'},HiveProtector:{Name:'Hive Protector'},Doomer:{Name:'Doomer'},Cypher:{Name:'Cypher'},Stinger:{Name:'Stinger'},CaptainWolf:{Name:'CaptainWolf'},Destroyer:{Name:'Destroyer'},Myst:{Name:'Myst'},Scarab:{Name:'Scarab'},Toxic:{Name:'Toxic'},Fist:{Name:'Fist'},Flag:{Name:'Flag'},DarkTaurus:{Name:'Dark Taurus'},Egg:{Name:'Egg'},Jumper:{Name:'Jumper'},BattleMoon:{Name:'Battle Moon'},MetallicBeard:{Name:'Metallic Beard'},DarkCrusader:{Name:'Dark Crusader'},Scourge:{Name:'Scourge'},Crawler:{Name:'Crawler'},Rain:{Name:'Rain'},Samurai:{Name:'Samurai'},Panther:{Name:'Panther'},Queen:{Name:'Queen'},DarkRain:{Name:'Dark Rain'},Worm:{Name:'Worm'},Taurus:{Name:'Taurus'},Kamikaze:{Name:'Kamikaze'},Pretorian:{Name:'Praetorian'},Seeker:{Name:'Seeker'},Nova:{Name:'Nova'},Maggot:{Name:'Maggot'},BlackWidow:{Name:'Black Widow'},Crusader:{Name:'Crusader'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Hive King'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Driller'},Eagle:{Name:'Eagle'},Blinker:{Name:'Blinker'},Sentry:{Name:'Sentry'},Vector:{Name:'Vector'},Walker:{Name:'Walker'},Titan:{Name:'Titan'},SilverBeard:{Name:'Silver Beard'},Fenix:{Name:'Fenix'},Interceptor:{Name:'Interceptor'},Reaper:{Name:'Reaper'},Raptor:{Name:'Raptor'},Spider:{Name:'Spider'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Heavy Seeker'}};</script>
	
</asp:Content>