<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/hr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Mobs
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Mobs</h1><p><div class="content">
  <u>mob</u> je neprijateljska jedinica koja je kontrolirana od strane umjetene inteligencije igte. Naletjeti ćete na mobs kada <a href='/hr/Universe/Travel.aspx'>Putovanje</a> <a href='/hr/Universe/Default.aspx'>Svemir</a>. Možete također raditi neke <a href='/hr/Quests.aspx'>Misije</a> gdje ćete trebati loviti određene mobove. Mobovi <a href='/hr/UnitIndex.aspx'>Borbene Jedinice</a> su jako moćni i možete dobiti neke za sebe kada izvršite <a href='/hr/Quests.aspx'>Misije</a> ili u <a href='/hr/Commerce/AuctionHouse.aspx'>Aukcijska Kuća</a>.
</div></p><table class='table'><tr><th>Rasa</td><th>Borbene Jedinice</td></tr><tr><td><a href='/hr/Race/Mercs.aspx'>Mercs</a></td><td><ul class='unitIndexList'><li><a href='/hr/Unit/Sentry.aspx'><img class='sentry' src='http://resources.orionsbelt.eu/Images/Common/Units/sentry.png' alt='Stražar' /></a></li><li><a href='/hr/Unit/Reaper.aspx'><img class='reaper' src='http://resources.orionsbelt.eu/Images/Common/Units/reaper.png' alt='Žetalica' /></a></li><li><a href='/hr/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Bič' /></a></li><li><a href='/hr/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li><li><a href='/hr/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titan' /></a></li><li><a href='/hr/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Srebrena Brada' /></a></li><li><a href='/hr/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Metalna Brada' /></a></li></ul></td></tr><tr><td>[SpaceForce]</td><td><ul class='unitIndexList'><li><a href='/hr/Unit/Jumper.aspx'><img class='jumper' src='http://resources.orionsbelt.eu/Images/Common/Units/jumper.png' alt='Jumper' /></a></li><li><a href='/hr/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/hr/Unit/Cypher.aspx'><img class='cypher' src='http://resources.orionsbelt.eu/Images/Common/Units/cypher.png' alt='Cypher' /></a></li><li><a href='/hr/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/hr/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Fist' /></a></li><li><a href='/hr/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Commander Fox' /></a></li><li><a href='/hr/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='CaptainWolf' /></a></li></ul></td></tr></table>
	
</asp:Content>