//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionsBelt.WebUserInterface {
    
    
    public partial class OrionsBeltTournament {
        
        /// <summary>
        /// InformationBoard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebUserInterface.Controls.InformationBoard InformationBoard1;
        
        /// <summary>
        /// ErrorBoard1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebUserInterface.Controls.ErrorBoard ErrorBoard1;
        
        /// <summary>
        /// Content control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ContentPlaceHolder Content;
        
        /// <summary>
        /// LatestPlayersOnline1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebUserInterface.Controls.LatestPlayersOnline LatestPlayersOnline1;
        
        /// <summary>
        /// UsefullLinks1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::OrionsBelt.WebUserInterface.Controls.UsefullLinks UsefullLinks1;
    }
}
