<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Sentinela
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Universo</h2><ul><li><a href='/pt/Universe/PrivateZone.aspx'>Zona Privada</a></li><li><a href='/pt/Universe/HotZone.aspx'>Zona Pública</a></li><li><a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a></li></ul><h2>Acções no Universo</h2><ul><li><a href='/pt/Universe/Travel.aspx'>Viajar</a></li><li><a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a></li><li><a href='/pt/Universe/Colonize.aspx'>Colonizar</a></li><li><a href='/pt/Universe/UniverseAttack.aspx'>Ataque</a></li><li><a href='/pt/Universe/Conquer.aspx'>Conquistar</a></li><li><a href='/pt/Universe/Raids.aspx'>Pilhagem</a></li><li><a href='/pt/Universe/UnloadCargo.aspx'>Descarregar Carga</a></li><li><a href='/pt/Universe/DevastationAttack.aspx'>Ataque Devastação</a></li></ul><h2>Elementos do Universo</h2><ul><li><a href='/pt/Universe/Planets.aspx'>Planetas</a></li><li><a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a></li><li><a href='/pt/Universe/Fleet.aspx'>Armada</a></li><li><a href='/pt/Universe/Arenas.aspx'>Arenas</a></li><li><a href='/pt/Universe/Beacon.aspx'>Sentinela</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Outros</h2><ul><li><a href='/pt/Universe/Alliance.aspx'>Aliança</a></li><li><a href='/pt/Universe/Relics.aspx'>Reliquias</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Sentinela</h1>
	<div class="content">
  <img src="/Resources/Images/BeaconImg.png" style="float:right;" alt="Sentinela" />
  <p>O <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> é a Arma Suprema dos <a href='/pt/Race/LightHumans.aspx'>Utopianos</a>. Como o nome indica, é algo que patrulha uma certa região do universo. E é exactamente isso.</p>
  <p>Quando crias um <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> ele vai, dependendo do seu nível, dar informações sobre a os <a href='/pt/Universe/Planets.aspx'>Planeta</a>s e <a href='/pt/Universe/Fleet.aspx'>Armada</a>s na reagião. Também previne o uso de <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a>s na região coberta por ele.</p>
  <p>O nível de um <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> é dado pela soma de níveis de tdos os <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> que possuis. Exemplo: se tiveres 3 <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> nível 1 e 1 <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> nível 2, o teu <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> terá nível 5.</p>
  <h1>Estados</h1>
    Podes ver qual o estado da criação de <a href='/pt/Universe/Beacon.aspx'>Sentinela</a>s no canto superior direito do ecrã. O <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> tem 4 estados:
    <ul><li><img src="/Resources/Images/pt/BeaconNotAvailable.gif" alt="Sentinela Não Disponível" title="Sentinela Não Disponível" /><br />
  O <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> não está construida em nenhum dos teus planetas.
 </li><li><img src="/Resources/Images/pt/BeaconNotReady.gif" alt="Sentinela não Pronta" title="Sentinela não Pronta" /><br />
   O <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> está construida, mas não tens recursos suficientes para a o criar.
  </li><li><img src="/Resources/Images/pt/BeaconReady.gif" alt="Sentinela Pronta" title="Sentinela Pronta" /><br />
   O <a class='deepspacescanner' href='/pt/Facility/DeepSpaceScanner.aspx'>Radar de Longo Alcance</a> está construido e podes criar um <a href='/pt/Universe/Beacon.aspx'>Sentinela</a>.
  </li><li><img src="/Resources/Images/pt/BeaconCooldown.gif" alt="Sentinela em Arrefecimento" title="Sentinela em Arrefecimento" /><br />
   O <a href='/pt/Universe/Beacon.aspx'>Sentinela</a> foi criado recentemente e está em arrefecimento.
  </li></ul><h1>Níveis</h1><ul><li>Nível 1 - Podes ver a quantidade unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a> uma <a href='/pt/Universe/Fleet.aspx'>Armada</a> tem. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 2 sectores todo à volta. Recarregamento leva 10 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>300 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>300 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>300 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>60 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>60 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>60 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>60 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>60 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 2 - Podes ver a quantidade unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a> e <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> uma <a href='/pt/Universe/Fleet.aspx'>Armada</a> tem. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 2 sectores todo à volta. Recarregamento leva 9 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>600 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>600 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>600 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>120 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>120 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>120 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>120 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>120 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 3 - Podes ver a quantidade unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a>, <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> e <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> uma <a href='/pt/Universe/Fleet.aspx'>Armada</a> tem. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 2 sectores todo à volta. Recarregamento leva 8 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>900 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>900 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>900 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>180 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>180 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>180 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>180 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>180 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 4 - Podes ver o tipo e quantidade de unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a> numa <a href='/pt/Universe/Fleet.aspx'>Armada</a> (bem como a quantidade de unidades <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> e <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a>). A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 3 sectores todo à volta. Recarregamento leva 7 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>1200 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1200 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1200 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>240 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>240 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>240 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>240 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>240 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 5 - Podes ver o tipo e quantidade de unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a> e <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> numa <a href='/pt/Universe/Fleet.aspx'>Armada</a> (bem como a quantidade de unidades <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a>). A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 3 sectores todo à volta. Recarregamento leva 6 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>1500 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1500 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1500 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>300 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>300 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>300 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>300 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>300 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 6 - Podes ver o tipo e quantidade de unidades <a href='/pt/Battles/Light.aspx'>Pequeno Porte</a>, <a href='/pt/Battles/Medium.aspx'>Médio Porte</a> e <a href='/pt/Battles/Heavy.aspx'>Grande Porte</a> numa <a href='/pt/Universe/Fleet.aspx'>Armada</a>. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 3 sectores todo à volta. Recarregamento leva 5 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>1800 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>1800 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>1800 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>360 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>360 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>360 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>360 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>360 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 7 - Podes ver os níveis dos edifícios num <a href='/pt/Universe/Planets.aspx'>Planeta</a>. O <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 4 sectores todo à volta. Recarregamento leva 4 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>2100 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2100 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2100 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>420 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>420 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>420 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>420 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>420 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 8 - Podes ver a produção de um <a href='/pt/Universe/Planets.aspx'>Planeta</a>. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 4 sectores todo à volta. Recarregamento leva 3 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>2400 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2400 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2400 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>480 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>480 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>480 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>480 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>480 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 9 - Podes ver a <a href='/pt/Universe/Fleet.aspx'>Armada</a> de defesa do <a href='/pt/Universe/Planets.aspx'>Planeta</a>. A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 4 sectores todo à volta. Recarregamento leva 2 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>2700 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>2700 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>2700 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>540 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>540 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>540 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>540 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>540 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 10 - A <a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a> é de 5 sectores todo à volta. Recarregamento leva 1 turnos.<br />
 Custo: <div id="resourcesCost"><ul><li>3000 <img title="Energy" alt="Energy" src="http://resources.orionsbelt.eu/Images/Common/Resources/EnergySmall.png" /></li><li>300 <img title="Mithril" alt="Mithril" src="http://resources.orionsbelt.eu/Images/Common/Resources/MithrilSmall.png" /></li><li>3000 <img title="Serium" alt="Serium" src="http://resources.orionsbelt.eu/Images/Common/Resources/SeriumSmall.png" /></li><li>600 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>600 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>600 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>600 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>600 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul><p>A figura abaixo ilustra a informação de todos os níveis:</p><img src="/Resources/Images/Beacon.png" alt="Beacon" title="Beacon" /></div>
</asp:Content>