<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Ataque Devastação
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Universo</h2><ul><li><a href='/pt/Universe/PrivateZone.aspx'>Zona Privada</a></li><li><a href='/pt/Universe/HotZone.aspx'>Zona Pública</a></li><li><a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a></li></ul><h2>Acções no Universo</h2><ul><li><a href='/pt/Universe/Travel.aspx'>Viajar</a></li><li><a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a></li><li><a href='/pt/Universe/Colonize.aspx'>Colonizar</a></li><li><a href='/pt/Universe/UniverseAttack.aspx'>Ataque</a></li><li><a href='/pt/Universe/Conquer.aspx'>Conquistar</a></li><li><a href='/pt/Universe/Raids.aspx'>Pilhagem</a></li><li><a href='/pt/Universe/UnloadCargo.aspx'>Descarregar Carga</a></li><li><a href='/pt/Universe/DevastationAttack.aspx'>Ataque Devastação</a></li></ul><h2>Elementos do Universo</h2><ul><li><a href='/pt/Universe/Planets.aspx'>Planetas</a></li><li><a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a></li><li><a href='/pt/Universe/Fleet.aspx'>Armada</a></li><li><a href='/pt/Universe/Arenas.aspx'>Arenas</a></li><li><a href='/pt/Universe/Beacon.aspx'>Sentinela</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Outros</h2><ul><li><a href='/pt/Universe/Alliance.aspx'>Aliança</a></li><li><a href='/pt/Universe/Relics.aspx'>Reliquias</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Ataque Devastação</h1>
	<div class="content">
  <p><a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> é a arma suprema dos <a href='/pt/Race/DarkHumans.aspx'>Renegados</a>. Está disponivel quando constrois o edificio <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a>.</p>
  <p>Quantos mais edificios deste tipo tiveres, mais poderosa a arma será. Se evoluires todas os edifícios <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> da tua zona privada para nível 2, terás a devastação com o poder máximo.</p>
  <h1>Estado</h1>
    Podes ver qual o estado da <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> no canto superior direito do ecrã. A <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> tem 4 estados:
    <ul><li><img src="/Resources/Images/pt/DevastationNotAvailable.gif" alt="Devastação Não Disponível" title="Devastação Não Disponível" /><br />
  <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> não está construida em nenhum dos teus planetas.
 </li><li><img src="/Resources/Images/pt/DevastacaoNaoPronta.gif" alt="Devastação não Pronta" title="Devastação não Pronta" /><br />
  <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> está construida mas não tens recursos suficientes para a disparar.
 </li><li><img src="/Resources/Images/pt/DevastacaoPronta.gif" alt="Devastação Pronta" title="Devastação Pronta" /><br />
  <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> está construida e podes disparar.
 </li><li><img src="/Resources/Images/pt/DevastacaoArrefecimento.gif" alt="Devastação em Arrefecimento" title="Devastação em Arrefecimento" /><br />
  <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> foi disparada recentemente e está em arrefecimento.
 </li></ul><h1>Utilização</h1><p>Podes usar a <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> a partir de qualquer <a href='/pt/Universe/Fleet.aspx'>Armada</a> disponível na <a href='/pt/Universe/HotZone.aspx'>Zona Pública</a>. Clica na <a href='/pt/Universe/Fleet.aspx'>Armada</a>, e de seguida clica no alvo (pode ser uma <a href='/pt/Universe/Fleet.aspx'>Armada</a>, um <a href='/pt/Universe/Planets.aspx'>Planeta</a> ou um região vazia no <a href='/pt/Universe/Default.aspx'>Universo</a>) tal como na figura abaixo:</p><img src="/Resources/Images/pt/DevastacaoDisparar.gif" alt="Disparar Devastação" title="Disparar Devastação" /><p><a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> não tem limite de alcance. Desde que haka uma zona com universo descoberto, a <a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> pode ser usada. Mas tem cuiado!!. A <b><a class='devastation' href='/pt/Facility/Devastation.aspx'>Devastação</a> afecta tanto as tuas <a href='/pt/Universe/Fleet.aspx'>Armada</a>s como as dos teus aliados</b>.</p><h1>Níveis</h1><ul><li>Nível 1 - Destroi 9% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> ou <a href='/pt/Universe/Planets.aspx'>Planeta</a> alvo. Só afecta uma coordenada.<br />
 Custo: <div id="resourcesCost"><ul><li>7000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>7000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>7000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>1000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>1000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>1000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>1000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>1000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 2 - Destroi 18% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> ou <a href='/pt/Universe/Planets.aspx'>Planeta</a> alvo. Só afecta uma coordenada.<br />
 Custo: <div id="resourcesCost"><ul><li>14000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>14000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>14000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>2000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>2000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>2000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>2000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>2000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 3 - Destroi 27% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> ou <a href='/pt/Universe/Planets.aspx'>Planeta</a> alvo. Só afecta uma coordenada.<br />
 Custo: <div id="resourcesCost"><ul><li>21000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>21000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>21000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>3000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>3000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>3000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>3000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>3000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 4 - Destroi 36% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> ou <a href='/pt/Universe/Planets.aspx'>Planeta</a> alvo. Só afecta uma coordenada.<br />
 Custo: <div id="resourcesCost"><ul><li>28000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>28000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>28000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>4000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>4000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>4000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>4000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>4000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 5 - Destroi 45% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> ou <a href='/pt/Universe/Planets.aspx'>Planeta</a> alvo. Só afecta uma coordenada.<br />
 Custo: <div id="resourcesCost"><ul><li>35000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>35000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>35000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>5000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>5000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>5000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>5000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>5000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 6 - Destroi 54% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> or <a href='/pt/Universe/Planets.aspx'>Planeta</a>. Afecta a coordenada alvo e todas as <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a> à sua volta(um total de 9 <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a>).<br />
 Custo: <div id="resourcesCost"><ul><li>42000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>42000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>42000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>6000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>6000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>6000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>6000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>6000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 7 - Destroi 63% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> or <a href='/pt/Universe/Planets.aspx'>Planeta</a>. Afecta a coordenada alvo e todas as <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a> à sua volta(um total de 9 <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a>).<br />
 Custo: <div id="resourcesCost"><ul><li>49000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>49000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>49000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>7000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>7000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>7000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>7000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>7000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 8 - Destroi 72% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> or <a href='/pt/Universe/Planets.aspx'>Planeta</a>. Afecta a coordenada alvo e todas as <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a> à sua volta(um total de 9 <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a>).<br />
 Custo: <div id="resourcesCost"><ul><li>65000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>65000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>65000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>10000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>10000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>10000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>10000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>10000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 9 - Destroi 81% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> or <a href='/pt/Universe/Planets.aspx'>Planeta</a>. Afecta a coordenada alvo e todas as <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a> à sua volta(um total de 9 <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a>).<br />
 Custo: <div id="resourcesCost"><ul><li>75000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>75000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>75000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>15000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>15000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>15000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>15000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>15000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 10 - Destroi 90% das unidades da <a href='/pt/Universe/Fleet.aspx'>Armada</a> or <a href='/pt/Universe/Planets.aspx'>Planeta</a>. Afecta a coordenada alvo e todas as <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a> a 2 de distância (um total de 25 <a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a>).<br />
 Custo: <div id="resourcesCost"><ul><li>90000 <img title="Gold" alt="Gold" src="http://resources.orionsbelt.eu/Images/Common/Resources/GoldSmall.png" /></li><li>90000 <img title="Titanium" alt="Titanium" src="http://resources.orionsbelt.eu/Images/Common/Resources/TitaniumSmall.png" /></li><li>90000 <img title="Uranium" alt="Uranium" src="http://resources.orionsbelt.eu/Images/Common/Resources/UraniumSmall.png" /></li><li>20000 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>20000 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>20000 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>20000 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>20000 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>