<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/pt/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Túnel Espacial
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Universo</h2><ul><li><a href='/pt/Universe/PrivateZone.aspx'>Zona Privada</a></li><li><a href='/pt/Universe/HotZone.aspx'>Zona Pública</a></li><li><a href='/pt/Universe/Coordinates.aspx'>Coordenadas</a></li></ul><h2>Acções no Universo</h2><ul><li><a href='/pt/Universe/Travel.aspx'>Viajar</a></li><li><a href='/pt/Universe/LineOfSight.aspx'>Área de Visão</a></li><li><a href='/pt/Universe/Colonize.aspx'>Colonizar</a></li><li><a href='/pt/Universe/UniverseAttack.aspx'>Ataque</a></li><li><a href='/pt/Universe/Conquer.aspx'>Conquistar</a></li><li><a href='/pt/Universe/Raids.aspx'>Pilhagem</a></li><li><a href='/pt/Universe/UnloadCargo.aspx'>Descarregar Carga</a></li><li><a href='/pt/Universe/DevastationAttack.aspx'>Ataque Devastação</a></li></ul><h2>Elementos do Universo</h2><ul><li><a href='/pt/Universe/Planets.aspx'>Planetas</a></li><li><a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a></li><li><a href='/pt/Universe/Fleet.aspx'>Armada</a></li><li><a href='/pt/Universe/Arenas.aspx'>Arenas</a></li><li><a href='/pt/Universe/Beacon.aspx'>Sentinela</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Outros</h2><ul><li><a href='/pt/Universe/Alliance.aspx'>Aliança</a></li><li><a href='/pt/Universe/Relics.aspx'>Reliquias</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Túnel Espacial</h1>
	<div class="content">
  <div style="float:right">
    <img src="/Resources/Images/pt/WormHole.png" alt="<a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>" title="<a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>" />
  </div>
  <p>O <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> é usado para instantaneamente transportar uma <a href='/pt/Universe/Fleet.aspx'>Armada</a> entre dois pontos do <a href='/pt/Universe/Default.aspx'>Universo</a>.</p>
  <p>Em todas as <a href='/pt/Universe/PrivateZone.aspx'>Zona Privada</a> existe um <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> que está ligado ao resto do <a href='/pt/Universe/Default.aspx'>Universo</a>. Está oculto por isso tens de explorar de modo a encontrares.
    Este <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> é igualmente privado. Isto significa que só tu és o único que o poderás usar. Em baixo está uma imagem da <a href='/pt/Universe/PrivateZone.aspx'>Zona Privada</a> descoberta 
    com o <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>.</p>
  <img src="/Resources/Images/PrivateWormHole.png" alt="<a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> Private" title="<a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> Privado" />
  <p>Para descobrir um <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> só precisas de o usar. Para isso clica numa <a href='/pt/Universe/Fleet.aspx'>Armada</a> e de seguida no <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>.
    Quando o fizeres, o seguinte menu irá aparecer:</p>
  <img src="/Resources/Images/Wormhole.png" alt="Worm Hole Popup" title="Worm Hole Popup" />
  <p>Al clicar na opção transporte, uma janela com todos os <a href='/pt/Universe/WormHole.aspx'>Túneis Espaciais</a> disponíveis aparece.</p>
  <p>Esta janela tens duas zonas de conteudo:
    <ul><li><a href='/pt/Universe/WormHole.aspx'>Túneis Espaciais</a> do Universo - Todos os <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> que já descobriste.</li><li><a href='/pt/Universe/WormHole.aspx'>Túneis Espaciais</a> da Aliança - Todos os <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> que a tua aliança (ou tu) have built (These <a href='/pt/Universe/WormHole.aspx'>Túneis Espaciais</a> can only be built buy the <a href='/pt/Race/Bugs.aspx'>Levyr</a>. See more information below).</li></ul></p>
  <h1><a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> dos <a href='/pt/Race/Bugs.aspx'>Levyr</a></h1>
  <p>This special kind of <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> is the <a href='/pt/Race/Bugs.aspx'>Levyr</a> ultimate weapon. This wormHole can be used only by you and, in higher stages of development, by the members of your alliance.</p>
  <p>
 Each built <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> has a level. Its level is given by the sum of the levels of your <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a>. Example: if you have 3 <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> level 1 and 1 <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> level 2,
 then your <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> level will be 5.
    </p>
  <h1>Estados</h1>
    Podes ver qual o estado do <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> no canto superior direito do ecrã. O <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> tem 4 estados:
    <ul><li><img src="/Resources/Images/pt/WormHoleNotAvailable.gif" alt="Túnel Espacial Não Disponível" title="Túnel Espacial Não Disponível" /><br />
  O <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> não está construido em nenhum dos teus planetas.
 </li><li><img src="/Resources/Images/pt/WormHoleNotReady.gif" alt="Túnel Espacial não Pronta" title="Túnel Espacial não Pronta" /><br />
   O <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> está construido mas não tens recursos suficientes para criar um <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>.
  </li><li><img src="/Resources/Images/pt/WormHoleReady.gif" alt="Túnel Espacial Pronta" title="Túnel Espacial Pronta" /><br />
   O <a class='wormholecreator' href='/pt/Facility/WormHoleCreator.aspx'>Gerador de Túneis Espaciais</a> está construido e podes criar um <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a>.
  </li><li><img src="/Resources/Images/pt/WormHoleCoolDown.gif" alt="Túnel Espacial em Arrefecimento" title="Túnel Espacial em Arrefecimento" /><br />
   Um <a href='/pt/Universe/WormHole.aspx'>Túnel Espacial</a> foi criado recentemente e está em arrefecimento.
  </li></ul><h1>Levels:</h1><ul><li>Nível 1 - Duração 1 dia. Período sem poder contruir de 10 dias. Só o dono o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>50 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>50 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>50 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>50 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>50 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 2 - Duração 2 dias. Período sem poder contruir de 9 dias. Só o dono o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>100 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>100 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>100 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>100 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>100 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 3 - Duração 3 dias. Período sem poder contruir de 8 dias. Só o dono o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>150 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>150 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>150 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>150 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>150 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 4 - Duração 4 dias. Período sem poder contruir de 7 dias. Só o dono e jogadores da mesma aliança e da raça <a href='/pt/Race/Bugs.aspx'>Levyr</a> (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>200 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>200 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>200 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>200 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>200 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 5 - Duração 5 dias. Período sem poder contruir de 6 dias. Só o dono e jogadores da mesma aliança e da raça <a href='/pt/Race/Bugs.aspx'>Levyr</a> (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>100 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>100 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>250 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>250 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>250 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>250 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>250 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 6 - Duração 6 dias. Período sem poder contruir de 5 dias. Só o dono e jogadores da mesma aliança e da raça <a href='/pt/Race/Bugs.aspx'>Levyr</a> (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>1200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>300 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>300 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>300 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>300 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>300 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 7 - Duração 7 dias. Período sem poder contruir de 4 dias. Só o dono e jogadores da mesma aliança e da raça <a href='/pt/Race/Bugs.aspx'>Levyr</a> (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>1400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>350 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>350 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>350 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>350 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>350 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 8 - Duração 8 dias. Período sem poder contruir de 3 dias. Só o dono e jogadores da mesma aliança (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>1600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>400 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>400 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>400 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>400 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>400 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 9 - Duração 9 dias. Período sem poder contruir de 2 dias. Só o dono e jogadores da mesma aliança (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>1800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>450 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>450 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>450 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>450 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>450 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Nível 10 - Duração 10 dias. Período sem poder contruir de 1 dias. Só o dono e jogadores da mesma aliança (Com nível 6 ou superior) o pode usar.<br />
 Custo: <div id="resourcesCost"><ul><li>2000 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>2000 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>500 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>500 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>500 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>500 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>500 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>