<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/de/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Wurmloch
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Universum</h2><ul><li><a href='/de/Universe/PrivateZone.aspx'>Privat-Zone</a></li><li><a href='/de/Universe/HotZone.aspx'>Öffentlice Zone</a></li><li><a href='/de/Universe/Coordinates.aspx'>Koordinaten</a></li></ul><h2>Universum Aktionen</h2><ul><li><a href='/de/Universe/Travel.aspx'>Reisen</a></li><li><a href='/de/Universe/LineOfSight.aspx'>Sichtlinie</a></li><li><a href='/de/Universe/Colonize.aspx'>Besiedeln</a></li><li><a href='/de/Universe/UniverseAttack.aspx'>Angriff</a></li><li><a href='/de/Universe/Conquer.aspx'>Erobern</a></li><li><a href='/de/Universe/Raids.aspx'>Plünderung</a></li><li><a href='/de/Universe/UnloadCargo.aspx'>Fracht abladen</a></li><li><a href='/de/Universe/DevastationAttack.aspx'>Zerstörungs-Attacke</a></li></ul><h2>Elemente des Universums</h2><ul><li><a href='/de/Universe/Planets.aspx'>Planeten</a></li><li><a href='/de/Universe/WormHole.aspx'>Wurmloch</a></li><li><a href='/de/Universe/Fleet.aspx'>Flotte</a></li><li><a href='/de/Universe/Arenas.aspx'>Arenen</a></li><li><a href='/de/Universe/Beacon.aspx'>Wachposten</a></li><li>[Academy]</li><li>[PirateBay]</li></ul><h2>Andere</h2><ul><li><a href='/de/Universe/Alliance.aspx'>Allianz</a></li><li><a href='/de/Universe/Relics.aspx'>Reliquien</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">
	
	<h1>Wurmloch</h1>
	<div class="content">
  <div style="float: right;">
    <img src="/Resources/Images/WormHole.png" alt="Worm Hole" title="Worm Hole" />
  </div>
  <p>Das <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> wird benutzt um eine <a href='/de/Universe/Fleet.aspx'>Flotte</a> unverzüglich von einem Punkt zum anderen im <a href='/de/Universe/Default.aspx'>Universum</a> zu transportieren.</p>
  <p>In jeder <a href='/de/Universe/PrivateZone.aspx'>Privat-Zone</a> gibt es ein <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> das dich mit dem Rest des <a href='/de/Universe/Default.aspx'>Universum</a> verbindet. Da es versteckt ist, musst du danach suchen.
 Das <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> ist auch privat. Das bedeutet dass du der einzige bist der es benutzen kann. Unten ist ein Bild einer unerforschten <a href='/de/Universe/PrivateZone.aspx'>Privat-Zone</a> mit dem <a href='/de/Universe/WormHole.aspx'>Wurmloch</a>.</p>
  <img src="/Resources/Images/PrivateWormHole.png" alt="Private Worm Hole" title="Private Worm Hole" />
  <p> Um ein neues Wurmloch zu erforschen musst du es nur benutzen. Dafür, musst du auf eine <a href='/de/Universe/Fleet.aspx'>Flotte</a> klicken und dann auf das<a href='/de/Universe/WormHole.aspx'>Wurmloch</a>. 
    Wenn du dies tust, erscheint das folgende Popup-Menü:</p>
  <img src="/Resources/Images/en/WormHole.png" alt="Worm Hole Popup" title="Worm Hole Popup" />
  <p>Wenn du Transport anklickst, erscheint ein Fenster mit allen verfügbaren <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a>.</p>
  <p>Diese Fenster hat 2 Tabs:
    </p>
  <ul>
    <li>Universe <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a> - Alle öffentlichen <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a> die du gefunden hast</li>
    <li>Alliance <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a> - Alle <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a> deiner Allianz oder die du gebaut hast (Diese <a href='/de/Universe/WormHole.aspx'>Wurmlöcher</a> können nur von den <a href='/de/Race/Bugs.aspx'>Levyr</a> gebaut werden. Mehr Information siehe unten).</li>
  </ul>
  <h1><a href='/de/Race/Bugs.aspx'>Levyr</a> Wormhole</h1>
  <p>Diese spezielle Art von <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> ist die ultimative Waffe der <a href='/de/Race/Bugs.aspx'>Levyr</a>. Dieses <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> kann nur von dir benutzt werden , und auf höheren Entwicklungsebenen, von den Mitgliedern deiner Allianz.</p>
  <p>
 Jedes gebaut <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> hat ein Level. Das Level wird angegeben durch die Summe der Level deines <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a>. Beispiel: Wenn du 3 <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> Level 1 und 1 <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> Level 2 hast,
 dann wird dein <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> Level 5 sein.
    </p>
  <h1>States</h1>
    Du kannst den Status in der oberen rechten Ecke des Bildschirms checken. Der <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> 
    hat 4 Zustände:
    <ul><li><img src="/Resources/Images/en/WormHoleNotAvailable.gif" alt="Wurmloch nicht verfügbar" title="Wurmloch nicht verfügbar" /><br />
  Der <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> wurde auf keinen deiner privaten Planeten gebaut.
 </li><li><img src="/Resources/Images/en/WormHoleNotReady.gif" alt="Wurmloch nicht bereit" title="Wurmloch nicht bereit" /><br />
   Der <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> ist gebaut hat aber nicht genügend Ressourcen um es erschaffen.
  </li><li><img src="/Resources/Images/en/WormHoleReady.gif" alt="Wurmloch bereit" title="Wurmloch bereit" /><br />
   Der <a class='wormholecreator' href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a> ist gebaut und kann ein <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> erzeugen.
  </li><li><img src="/Resources/Images/en/WormHoleCoolDown.gif" alt="Wurmloch Abkühlung" title="Wurmloch Abkühlung" /><br />
   Ein <a href='/de/Universe/WormHole.aspx'>Wurmloch</a> wurde kürzlich erzuegt und ist in der Abkühlungsphase.
  </li></ul><h1>Levels:</h1><ul><li>Level 1 - Dauer 1 Tag. Konstruktion-Abkühlungsphase von 10 Tagen. 
 Nur der Besitzer kann es benutzen.<br />
 Cost: <div id="resourcesCost"><ul><li>200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>50 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>50 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>50 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>50 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>50 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 2 - Duration 2 days. Construction cooldown of 9 days. Only the owner can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>100 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>100 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>100 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>100 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>100 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 3 - Duration 3 days. Construction cooldown of 8 days. Only the owner can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>150 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>150 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>150 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>150 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>150 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 4 - Duration 4 days. Construction cooldown of 7 days. Only the owner and players of the same alliance and from the <a href='/de/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>200 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>200 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>200 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>200 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>200 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 5 - Duration 5 days. Construction cooldown of 6 days. Only the owner and players of the same alliance and from the <a href='/de/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>100 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>100 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>250 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>250 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>250 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>250 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>250 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 6 - Duration 6 days. Construction cooldown of 5 days. Only the owner and players of the same alliance and from the <a href='/de/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1200 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1200 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>300 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>300 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>300 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>300 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>300 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 7 - Duration 7 days. Construction cooldown of 4 days. Only the owner and players of the same alliance and from the <a href='/de/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1400 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1400 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>350 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>350 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>350 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>350 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>350 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 8 - Duration 8 days. Construction cooldown of 3 days. Only the owner and players of the same alliance and from thee <a href='/de/Race/Bugs.aspx'>Levyr</a> (with level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1600 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1600 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>400 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>400 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>400 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>400 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>400 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 9 - Duration 9 days. Construction cooldown of 2 days. Only the owner and players of the same alliance (with Level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>1800 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>1800 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>450 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>450 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>450 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>450 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>450 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li><li>Level 10 - Duration 10 days. Construction cooldown of 1 days. Only the owner and players of the same alliance (with Level 6 or above) can use it.<br />
 Cost: <div id="resourcesCost"><ul><li>2000 <img title="Protol" alt="Protol" src="http://resources.orionsbelt.eu/Images/Common/Resources/ProtolSmall.png" /></li><li>2000 <img title="Elk" alt="Elk" src="http://resources.orionsbelt.eu/Images/Common/Resources/ElkSmall.png" /></li><li>500 <img title="Astatine" alt="Astatine" src="http://resources.orionsbelt.eu/Images/Common/Resources/AstatineSmall.png" /></li><li>500 <img title="Prismal" alt="Prismal" src="http://resources.orionsbelt.eu/Images/Common/Resources/PrismalSmall.png" /></li><li>500 <img title="Argon" alt="Argon" src="http://resources.orionsbelt.eu/Images/Common/Resources/ArgonSmall.png" /></li><li>500 <img title="Cryptium" alt="Cryptium" src="http://resources.orionsbelt.eu/Images/Common/Resources/CryptiumSmall.png" /></li><li>500 <img title="Radon" alt="Radon" src="http://resources.orionsbelt.eu/Images/Common/Resources/RadonSmall.png" /></li></ul></div></li></ul></div>
	
</asp:Content>