<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/en/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Mobs
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Mobs</h1><p><div class="content">
    A <u>mob</u> is an enemy that is controled by the game(artificial intelligence). You'll run into mobs while you <a href='/en/Universe/Travel.aspx'>Travel</a> on
    the <a href='/en/Universe/Default.aspx'>Universe</a>. You may also do some <a href='/en/Quests.aspx'>Quests</a> where you'll need to hunt down certain mobs. The mobs <a href='/en/UnitIndex.aspx'>Combat Units</a> are very powerful, and you may
    get some for your own by doing some <a href='/en/Quests.aspx'>Quests</a> or on the <a href='/en/Commerce/AuctionHouse.aspx'>Auction House</a>.
  </div></p><table class='table'><tr><th>Race</td><th>Combat Units</td></tr><tr><td><a href='/en/Race/Mercs.aspx'>Mercs</a></td><td><ul class='unitIndexList'><li><a href='/en/Unit/Sentry.aspx'><img class='sentry' src='http://resources.orionsbelt.eu/Images/Common/Units/sentry.png' alt='Sentry' /></a></li><li><a href='/en/Unit/Reaper.aspx'><img class='reaper' src='http://resources.orionsbelt.eu/Images/Common/Units/reaper.png' alt='Reaper' /></a></li><li><a href='/en/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Scourge' /></a></li><li><a href='/en/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li><li><a href='/en/Unit/Titan.aspx'><img class='titan' src='http://resources.orionsbelt.eu/Images/Common/Units/titan.png' alt='Titan' /></a></li><li><a href='/en/Unit/SilverBeard.aspx'><img class='silverbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/silverbeard.png' alt='Silver Beard' /></a></li><li><a href='/en/Unit/MetallicBeard.aspx'><img class='metallicbeard' src='http://resources.orionsbelt.eu/Images/Common/Units/metallicbeard.png' alt='Metallic Beard' /></a></li></ul></td></tr><tr><td>[SpaceForce]</td><td><ul class='unitIndexList'><li><a href='/en/Unit/Jumper.aspx'><img class='jumper' src='http://resources.orionsbelt.eu/Images/Common/Units/jumper.png' alt='Jumper' /></a></li><li><a href='/en/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/en/Unit/Cypher.aspx'><img class='cypher' src='http://resources.orionsbelt.eu/Images/Common/Units/cypher.png' alt='Cypher' /></a></li><li><a href='/en/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/en/Unit/Fist.aspx'><img class='fist' src='http://resources.orionsbelt.eu/Images/Common/Units/fist.png' alt='Fist' /></a></li><li><a href='/en/Unit/CommanderFox.aspx'><img class='commanderfox' src='http://resources.orionsbelt.eu/Images/Common/Units/commanderfox.png' alt='Commander Fox' /></a></li><li><a href='/en/Unit/CaptainWolf.aspx'><img class='captainwolf' src='http://resources.orionsbelt.eu/Images/Common/Units/captainwolf.png' alt='CaptainWolf' /></a></li></ul></td></tr></table>
	
</asp:Content>