<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/hr/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Srednji
</asp:Content>

<asp:Content ContentPlaceHolderID="conceptMenu" runat="server">
	<h2>Borbeni Koncepti</h2><ul><li><a href='/hr/Battles/GameBoard.aspx'>Tabla Igre</a></li><li><a href='/hr/Battles/Deploy.aspx'>Raspoređivanje</a></li><li><a href='/hr/Battles/Movement.aspx'>Pokret</a></li><li><a href='/hr/Battles/Rules.aspx'>Rules</a></li></ul><h2>Napad</h2><ul><li><a href='/hr/Battles/Range.aspx'>Domet</a></li><li><a href='/hr/Battles/Catapult.aspx'>Katapult</a></li><li><a href='/hr/Battles/ParalyseAttack.aspx'>Napad Paralize</a></li><li><a href='/hr/Battles/Replicator.aspx'>Replikator</a></li><li><a href='/hr/Battles/StrikeBack.aspx'>Protunapad</a></li><li><a href='/hr/Battles/InfestationAttack.aspx'>Napad Obuzetosti</a></li><li><a href='/hr/Battles/RemoveAbilityAttack.aspx'>Makni Sposobnost Napad</a></li><li><a href='/hr/Battles/TripleAttack.aspx'>Trostruki Napad</a></li><li><a href='/hr/Battles/BombAttack.aspx'>Napad Bombom</a></li><li><a href='/hr/Battles/Rebound.aspx'>Povratni</a></li></ul><h2>Kategorija</h2><ul><li><a href='/hr/Battles/Light.aspx'>Lagani</a></li><li><a href='/hr/Battles/Medium.aspx'>Srednji</a></li><li><a href='/hr/Battles/Heavy.aspx'>Teški</a></li><li><a href='/hr/Battles/Ultimate.aspx'>Ultimativni</a></li><li><a href='/hr/Battles/Special.aspx'>Izvanredni</a></li></ul><h2>Tip Bitke</h2><ul><li><a href='/hr/Battles/TotalAnnihilation.aspx'>Totalno Uništenje</a></li><li><a href='/hr/Battles/Regicide.aspx'>Regicid</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1>Srednje Jedinice</h1>
<div class="content">
<a href='/hr/Battles/Medium.aspx'>Srednji</a> su najbalansiranije jedinice u igri. Nisu najbrže niti su najsporije. Nisu najjače ali nisu ni najslabije. Balans snage i slobode <a href='/hr/Battles/Movement.aspx'>Pokret</a> čini <a href='/hr/Battles/Medium.aspx'>Srednji</a> jedinice srcem svake <a href='/hr/Universe/Fleet.aspx'>Flota</a>.
<p />
<a href='/hr/Battles/Medium.aspx'>Srednji</a> mogu biti slabije nego <a href='/hr/Battles/Heavy.aspx'>Teški</a> jedinice, ali mnogo puta ekstra mobilnost sa malom pomoći <a href='/hr/Battles/DispensableUnits.aspx'>Hrana za Topove</a> pretvara ih u pobjednike. Kao prirodne neprijatelje, <a href='/hr/Battles/Medium.aspx'>Srednji</a> jedinice bi trebale izbjeći <a class='kamikaze' href='/hr/Unit/Kamikaze.aspx'>Kamikaza</a> i <a class='seeker' href='/hr/Unit/Seeker.aspx'>Tražilac</a>.
<p />
<a href='/hr/Battles/Medium.aspx'>Srednji</a> jedinice:
</div>
	<ul class='imageList'><li><a href='/hr/Unit/Kamikaze.aspx'><img class='kamikaze' src='http://resources.orionsbelt.eu/Images/Common/Units/kamikaze.png' alt='Kamikaza' /></a></li><li><a href='/hr/Unit/Spider.aspx'><img class='spider' src='http://resources.orionsbelt.eu/Images/Common/Units/spider.png' alt='Pauk' /></a></li><li><a href='/hr/Unit/HiveProtector.aspx'><img class='hiveprotector' src='http://resources.orionsbelt.eu/Images/Common/Units/hiveprotector.png' alt='Zaštitnik Košnice' /></a></li><li><a href='/hr/Unit/Driller.aspx'><img class='driller' src='http://resources.orionsbelt.eu/Images/Common/Units/driller.png' alt='Bušitelj' /></a></li><li><a href='/hr/Unit/Vector.aspx'><img class='vector' src='http://resources.orionsbelt.eu/Images/Common/Units/vector.png' alt='Vector' /></a></li><li><a href='/hr/Unit/Worm.aspx'><img class='worm' src='http://resources.orionsbelt.eu/Images/Common/Units/worm.png' alt='Glista' /></a></li><li><a href='/hr/Unit/Scourge.aspx'><img class='scourge' src='http://resources.orionsbelt.eu/Images/Common/Units/scourge.png' alt='Bič' /></a></li><li><a href='/hr/Unit/Kahuna.aspx'><img class='kahuna' src='http://resources.orionsbelt.eu/Images/Common/Units/kahuna.png' alt='Kahuna' /></a></li><li><a href='/hr/Unit/Scarab.aspx'><img class='scarab' src='http://resources.orionsbelt.eu/Images/Common/Units/scarab.png' alt='Kornjaš' /></a></li><li><a href='/hr/Unit/Eagle.aspx'><img class='eagle' src='http://resources.orionsbelt.eu/Images/Common/Units/eagle.png' alt='Orao' /></a></li><li><a href='/hr/Unit/Pretorian.aspx'><img class='pretorian' src='http://resources.orionsbelt.eu/Images/Common/Units/pretorian.png' alt='Pretorijanac' /></a></li><li><a href='/hr/Unit/Stinger.aspx'><img class='stinger' src='http://resources.orionsbelt.eu/Images/Common/Units/stinger.png' alt='Žalac' /></a></li><li><a href='/hr/Unit/Krill.aspx'><img class='krill' src='http://resources.orionsbelt.eu/Images/Common/Units/krill.png' alt='Krill' /></a></li><li><a href='/hr/Unit/Destroyer.aspx'><img class='destroyer' src='http://resources.orionsbelt.eu/Images/Common/Units/destroyer.png' alt='Razarač' /></a></li><li><a href='/hr/Unit/Myst.aspx'><img class='myst' src='http://resources.orionsbelt.eu/Images/Common/Units/myst.png' alt='Myst' /></a></li><li><a href='/hr/Unit/Crawler.aspx'><img class='crawler' src='http://resources.orionsbelt.eu/Images/Common/Units/crawler.png' alt='Crawler' /></a></li><li><a href='/hr/Unit/Walker.aspx'><img class='walker' src='http://resources.orionsbelt.eu/Images/Common/Units/walker.png' alt='Walker' /></a></li></ul>
	<script type='text/javascript'>window.unitTips = {Attack:'Napad',Defense:'Obrana',MovementCost:'Cijena Pokreta',Range:'Domet',Bozer:{Name:'Bozer'},CommanderFox:{Name:'Commander Fox'},HiveProtector:{Name:'Zaštitnik Košnice'},Doomer:{Name:'Anihilator'},Cypher:{Name:'Cypher'},Stinger:{Name:'Žalac'},CaptainWolf:{Name:'CaptainWolf'},Destroyer:{Name:'Razarač'},Myst:{Name:'Myst'},Scarab:{Name:'Kornjaš'},Toxic:{Name:'Otrovni'},Fist:{Name:'Fist'},Flag:{Name:'Zastava'},DarkTaurus:{Name:'Tamni Bik'},Egg:{Name:'Jaje'},Jumper:{Name:'Jumper'},BattleMoon:{Name:'Borbeni Mjesec'},MetallicBeard:{Name:'Metalna Brada'},DarkCrusader:{Name:'Crni Crusader'},Scourge:{Name:'Bič'},Crawler:{Name:'Crawler'},Rain:{Name:'Kiša'},Samurai:{Name:'Samuraj'},Panther:{Name:'Pantera'},Queen:{Name:'Kraljica'},DarkRain:{Name:'Crna Kiša'},Worm:{Name:'Glista'},Taurus:{Name:'Bik'},Kamikaze:{Name:'Kamikaza'},Pretorian:{Name:'Pretorijanac'},Seeker:{Name:'Tražilac'},Nova:{Name:'Nova'},Maggot:{Name:'Crv'},BlackWidow:{Name:'Crna Udovica'},Crusader:{Name:'Crusader'},Anubis:{Name:'Anubis'},HiveKing:{Name:'Kralj Košnice'},Kahuna:{Name:'Kahuna'},Driller:{Name:'Bušitelj'},Eagle:{Name:'Orao'},Blinker:{Name:'Bljeskalica'},Sentry:{Name:'Stražar'},Vector:{Name:'Vector'},Walker:{Name:'Walker'},Titan:{Name:'Titan'},SilverBeard:{Name:'Srebrena Brada'},Fenix:{Name:'Feniks'},Interceptor:{Name:'Presretač'},Reaper:{Name:'Žetalica'},Raptor:{Name:'Raptor'},Spider:{Name:'Pauk'},Krill:{Name:'Krill'},HeavySeeker:{Name:'Teški Tražilac'}};</script>
	
</asp:Content>