<%@ Page Language="C#" AutoEventWireup="false" MasterPageFile="~/de/Resources.Master" %>

<asp:Content ContentPlaceHolderID="title" runat="server">
	Blinker Fabrik Gebäude
</asp:Content>

<asp:Content ContentPlaceHolderID="menu" runat="server">
	<h2>Gebäude</h2><ul><li><a href='/de/Facility/BlinkerAssembler.aspx'>Blinker Fabrik</a></li><li><a href='/de/Facility/Extractor.aspx'>Extraktor</a></li><li><a href='/de/Facility/BattleMoonAssembler.aspx'>Fabrik der Mondschlachten</a></li><li><a href='/de/Facility/DarknessHall.aspx'>Halle der Dunkelheit</a></li><li><a href='/de/Facility/DominationYard.aspx'>Herrschafts Hangar</a></li><li><a href='/de/Facility/Incubator.aspx'>Inkubator</a></li><li><a href='/de/Facility/QueenHatchery.aspx'>Königin Brutstätte</a></li><li><a href='/de/Facility/MithrilExtractor.aspx'>Mithril Extraktor</a></li><li><a href='/de/Facility/ElkExtractor.aspx'>Nahrungsextraktor</a></li><li><a href='/de/Facility/Nest.aspx'>Nest</a></li><li><a href='/de/Facility/ProtolExtractor.aspx'>Protol Extraktor</a></li><li><a href='/de/Facility/SeriumExtractor.aspx'>Serium Extraktor</a></li><li><a href='/de/Facility/Silo.aspx'>Silo</a></li><li><a href='/de/Facility/SlaveWarehouse.aspx'>Sklaven Warenlager</a></li><li><a href='/de/Facility/SolarPanel.aspx'>Solar Tafel</a></li><li><a href='/de/Facility/TitaniumExtractor.aspx'>Titanium Extraktor</a></li><li><a href='/de/Facility/NuclearFacility.aspx'>Uranium Extraktor</a></li><li><a href='/de/Facility/DeepSpaceScanner.aspx'>Weltraum Tiefenscanner</a></li><li><a href='/de/Facility/UnitYard.aspx'>Weltraumhafen</a></li><li><a href='/de/Facility/WormHoleCreator.aspx'>Wurmloch Erzeuger</a></li><li><a href='/de/Facility/CommandCenter.aspx'>Zentralkommando</a></li><li><a href='/de/Facility/Devastation.aspx'>Zerstörung</a></li><li><a href='/de/Facility/DevotionSanctuary.aspx'>Zufluchtsstätte der Hingabe</a></li></ul>
</asp:Content>

<asp:Content ContentPlaceHolderID="content" runat="server">

	<h1><asp:Literal Text="Blinker Fabrik" runat="server" /></h1>

	<div class="description">
		Der <a class='blinkerassembler' href='/de/Facility/BlinkerAssembler.aspx'>Blinker Fabrik</a> ist ein <a href='/de/Race/LightHumans.aspx'>Utopians</a> Gebäude das ihnen erlaubt ihre <a href='/de/Battles/Ultimate.aspx'>Höchste</a> Einheit zu bauen: der <a class='blinker' href='/de/Unit/Blinker.aspx'>Blinker</a>.
		<img src='http://resources.orionsbelt.eu/Images/Common/Planets/LightHumans/BlinkerAssemblerR.png' alt='Blinker Fabrik' />
	</div>
	<div class="clear"></div>
	<h2><a href='#Level1' name='Level1'>Blinker Fabrik Level 1</a></h2><table class='table'><tr><th>Abhängigkeiten</th><th>Kosten</th><th>Dauer</th><th>Wenn es fertig ist</th><th>Freigeben</th></tr><tr><td><ul><li><a href='../Facility/CommandCenter.aspx'>Zentralkommando</a> Level 8</li></ul></td><td><ul><li>28000 <a href='../Intrinsic/Mithril.aspx'>Mithril</a></li><li>25000 <a href='../Intrinsic/Serium.aspx'>Serium</a></li><li>26000 <a href='../Intrinsic/Energy.aspx'>Energie</a></li><li>4000 <a href='../Intrinsic/Argon.aspx'>Argon</a></li><li>3500 <a href='../Intrinsic/Radon.aspx'>Radon</a></li><li>3500 <a href='../Intrinsic/Astatine.aspx'>Astatine</a></li></ul></td><td class='duration'>1 Tag 6 Stunden </td><td><ul><li>+2500 Spielstand</li></ul></td><td><ul><li><a href='../Unit/Blinker.aspx'>Blinker</a></li></ul></td></tr></table><h2><a href='#Level2' name='Level2'>Blinker Fabrik Level 2</a></h2><table class='table'><tr><th>Abhängigkeiten</th><th>Kosten</th><th>Dauer</th><th>Wenn es fertig ist</th><th>Freigeben</th></tr><tr><td><ul><li><a href='../Facility/UnitYard.aspx'>Weltraumhafen</a> Level 10</li></ul></td><td><ul><li>56000 <a href='../Intrinsic/Mithril.aspx'>Mithril</a></li><li>50000 <a href='../Intrinsic/Serium.aspx'>Serium</a></li><li>52000 <a href='../Intrinsic/Energy.aspx'>Energie</a></li><li>8000 <a href='../Intrinsic/Argon.aspx'>Argon</a></li><li>5000 <a href='../Intrinsic/Prismal.aspx'>Prismal</a></li><li>7000 <a href='../Intrinsic/Radon.aspx'>Radon</a></li><li>7000 <a href='../Intrinsic/Astatine.aspx'>Astatine</a></li></ul></td><td class='duration'>2 Tage 12 Stunden </td><td><ul><li>+5000 Spielstand</li></ul></td><td><ul></ul></td></tr></table>
	
</asp:Content>