#!/bin/bash

PID=`cat /var/run/php-fastcgi.pid`
echo "php fastcgi pid: $PID"

if ! ps -p $PID > /dev/null
then
	echo "No server found..."
	echo "Launching php fastcgi..."
	/usr/bin/php-fastcgi
	echo "New process lanuched!"
else
	echo "Already running!"
fi
